export const carBrandImageBrands = [
  "acura",
  "alfa-romeo",
  "am-general",
  "bajaj",
  "aston-martin",
  "ashok-layland",
  "audi",
  "bentley",
  "bharat-benz",
  "bmw",
  "bugatti",
  "buick",
  "byd",
  "cadillac",
  "chevrolet",
  "chrysler",
  "citroen",
  "dacia",
  "daewoo",
  "dc",
  "eagle",
  "eicher",
  "ferrari",
  "fiat",
  "fisker",
  "ford",
  "genesis",
  "geo",
  "gmc",
  "honda",
  "hummer",
  "hindustan-motors",
  "hyundai",
  "icml",
  "infiniti",
  "isuzu",
  "jaguar",
  "jeep",
  "kia",
  "lamborghini",
  "land-rover",
  "leap-motor",
  "lexus",
  "lincoln",
  "lotus",
  "mahindra",
  "maserati",
  "maybach",
  "mazda",
  "mclaren",
  "mercedes-benz",
  "mercury",
  "mg",
  "mini",
  "mitsubishi",
  "nissan",
  "oldsmobile",
  "opel",
  "panoz",
  "perodua",
  "peugeot",
  "plymouth",
  "pmv",
  "pontiac",
  "porsche",
  "pravaig",
  "premier",
  "dodge",
  "renault",
  "rolls-royce",
  "rover",
  "saab",
  "san",
  "saturn",
  "scion",
  "seat",
  "skoda",
  "smart",
  "smpil",
  "spyker",
  "strom-motors",
  "subaru",
  "suzuki",
  "tata",
  "tesla",
  "toyota",
  "vayve-mobility",
  "vinfast",
  "volkswagen",
  "volvo",
  "zanella",
  "daihatsu",
  "w-motors",
  "rox",
  "avatr",
  "baic",
  "brilliance",
  "ram",
  "luxgen",
  "rabdan",
  "jetour",
  "gac",
  "xiaomi",
  "seres",
  "alpina",
  "jac",
  "geely",
  "bestune",
  "skywell",
  "changan",
  "abarth",
  "chery",
  "land-rover-alt",
  "holden",
  "isuzu-alt",
  "gwm",
  "cupra",
  "range-rover",
  "ssangyong",
  "haval",
  "ldv"
] as const;

export const carBrandVectorBrands = [
  "acura",
  "alfa-romeo",
  "am-general",
  "bajaj",
  "aston-martin",
  "ashok-layland",
  "audi",
  "bentley",
  "bharat-benz",
  "bmw",
  "bugatti",
  "buick",
  "byd",
  "cadillac",
  "chevrolet",
  "chrysler",
  "citroen",
  "dacia",
  "daewoo",
  "dc",
  "eagle",
  "eicher",
  "ferrari",
  "fiat",
  "fisker",
  "ford",
  "genesis",
  "geo",
  "gmc",
  "honda",
  "hummer",
  "hindustan-motors",
  "hyundai",
  "icml",
  "infiniti",
  "isuzu",
  "jaguar",
  "jeep",
  "kia",
  "lamborghini",
  "land-rover",
  "leap-motor",
  "lexus",
  "lincoln",
  "lotus",
  "mahindra",
  "maserati",
  "maybach",
  "mazda",
  "mclaren",
  "mercedes-benz",
  "mercury",
  "mg",
  "mini",
  "mitsubishi",
  "nissan",
  "oldsmobile",
  "opel",
  "panoz",
  "perodua",
  "peugeot",
  "plymouth",
  "pmv",
  "pontiac",
  "porsche",
  "pravaig",
  "premier",
  "dodge",
  "renault",
  "rolls-royce",
  "rover",
  "saab",
  "san",
  "saturn",
  "scion",
  "seat",
  "skoda",
  "smart",
  "smpil",
  "spyker",
  "strom-motors",
  "subaru",
  "suzuki",
  "tata",
  "tesla",
  "toyota",
  "vayve-mobility",
  "vinfast",
  "volkswagen",
  "volvo",
  "zanella"
] as const;

export type CarBrandImageBrand = (typeof carBrandImageBrands)[number];
export type CarBrandVectorBrand = (typeof carBrandVectorBrands)[number];
export type CarBrandLogoBrand = CarBrandImageBrand | CarBrandVectorBrand;
export type CarBrandLogoAssetType = "image" | "vector";
export type CarBrandLogoAspectRatio = "4:3" | "1:1";

const brandLabelOverrides: Partial<Record<CarBrandLogoBrand, string>> = {
  icml: "ICML",
  mg: "MG",
  dc: "DC",
  byd: "BYD",
  gmc: "GMC",
  pmv: "PMV",
  smpil: "SMPIL",
  ldv: "LDV",
  haval: "HAVAL",
  jac: "JAC",
  gac: "GAC",
  gwm: "GWM",
  ram: "RAM",
  "w-motors": "W Motors",
  "land-rover-alt": "Land_rover",
  "isuzu-alt": "Isuzu",
  "range-rover": "Range-rover"
};

const imageBrandSet = new Set<string>(carBrandImageBrands);
const vectorBrandSet = new Set<string>(carBrandVectorBrands);

export function getCarBrandLogoLabel(brand: CarBrandLogoBrand) {
  const override = brandLabelOverrides[brand];

  if (override) {
    return override;
  }

  return brand
    .replace(/-alt$/, "")
    .split("-")
    .map((segment) => segment.charAt(0).toUpperCase() + segment.slice(1))
    .join(" ");
}

export function hasCarBrandLogoAsset(brand: CarBrandLogoBrand, assetType: CarBrandLogoAssetType) {
  return assetType === "image" ? imageBrandSet.has(brand) : vectorBrandSet.has(brand);
}

export const totalCarBrandImageCount = carBrandImageBrands.length;
export const totalCarBrandVectorCount = carBrandVectorBrands.length;
