import { governanceRules } from "./governance";
import type { DesignSystemRegistry } from "./types";

export const designSystemRegistry: DesignSystemRegistry = {
  governance: governanceRules,
  components: [
    {
      canonicalId: "component.button",
      canonicalName: "Button",
      layer: "component",
      status: "approved",
      platform: "shared",
      figmaComponentName: "Button",
      description: "Primary canonical action component.",
      webExport: "@geist/web/canonical/button",
      nativeExport: "@geist/native/canonical/button",
      variants: [
        { name: "shape", values: ["Regular", "Pill"] },
        { name: "styleVariant", values: ["Solid", "Outline", "Ghost", "Transparent", "Destructive"] },
        { name: "size", values: ["Extra Small", "Small", "Medium", "Large", "Extra Large"] },
        { name: "onDark", values: ["false", "true"] },
        { name: "loading", values: ["false", "true"] },
        { name: "disabled", values: ["false", "true"] }
      ],
      states: ["rest", "hover", "pressed", "disabled", "loading", "focus"],
      tokenBindings: [
        { slot: "radius.regular.xs", token: "var(--radius/sm)" },
        { slot: "radius.regular.sm", token: "var(--radius/sm)" },
        { slot: "radius.regular.md", token: "var(--radius/md)" },
        { slot: "radius.regular.lg", token: "var(--radius/lg)" },
        { slot: "radius.regular.xl", token: "var(--radius/xl)" },
        { slot: "radius.pill", token: "var(--cars24-theme-radius-full)" },
        { slot: "size.xs.minWidth", token: "90px" },
        { slot: "size.xs.height", token: "28px" },
        { slot: "size.xs.gap", token: "4px" },
        { slot: "size.xs.paddingInline", token: "12px" },
        { slot: "size.xs.paddingBlock", token: "5px" },
        { slot: "size.xs.typography", token: "Mobile/Body3 - 11/semibold" },
        { slot: "size.sm.minWidth", token: "95px" },
        { slot: "size.sm.height", token: "32px" },
        { slot: "size.sm.gap", token: "4px" },
        { slot: "size.sm.paddingInline", token: "12px" },
        { slot: "size.sm.paddingBlock", token: "7px" },
        { slot: "size.sm.typography", token: "Mobile/Body2 - 13/semibold" },
        { slot: "size.md.minWidth", token: "112px" },
        { slot: "size.md.height", token: "40px" },
        { slot: "size.md.gap", token: "6px" },
        { slot: "size.md.paddingInline", token: "14px" },
        { slot: "size.md.paddingBlock", token: "10px" },
        { slot: "size.md.typography", token: "Mobile/Body1 - 15/semibold" },
        { slot: "size.lg.minWidth", token: "124px" },
        { slot: "size.lg.height", token: "44px" },
        { slot: "size.lg.gap", token: "6px" },
        { slot: "size.lg.paddingInline", token: "16px" },
        { slot: "size.lg.paddingBlock", token: "12px" },
        { slot: "size.lg.typography", token: "Mobile/Body1 - 15/semibold" },
        { slot: "size.xl.minWidth", token: "130px" },
        { slot: "size.xl.height", token: "56px" },
        { slot: "size.xl.gap", token: "6px" },
        { slot: "size.xl.paddingInline", token: "18px" },
        { slot: "size.xl.paddingBlock", token: "18px" },
        { slot: "size.xl.typography", token: "Mobile/Heading4 - 17/semibold" },
        { slot: "focusRing", token: "color.border.focus" },
        { slot: "surface.light.solid.rest.background", token: "var(--cars24-semantic-bg-brand-base)" },
        { slot: "surface.light.solid.hover.background", token: "var(--cars24-semantic-bg-brand-base-hover)" },
        { slot: "surface.light.solid.foreground", token: "var(--cars24-semantic-text-primary-inverse)" },
        { slot: "surface.light.outline.rest.border", token: "var(--cars24-semantic-border-brand-base)" },
        { slot: "surface.light.outline.hover.border", token: "var(--cars24-semantic-border-brand-base-alt)" },
        { slot: "surface.light.outline.hover.background", token: "var(--cars24-semantic-bg-brand-subtler)" },
        { slot: "surface.light.outline.foreground", token: "var(--cars24-semantic-text-brand-base)" },
        { slot: "surface.light.ghost.hover.background", token: "var(--cars24-semantic-bg-brand-subtler)" },
        { slot: "surface.light.ghost.foreground", token: "var(--cars24-semantic-text-brand-base)" },
        { slot: "surface.light.transparent.rest.background", token: "var(--cars24-utility-alpha-black-200)" },
        { slot: "surface.light.transparent.hover.background", token: "var(--cars24-utility-alpha-black-300)" },
        { slot: "surface.light.transparent.foreground", token: "var(--cars24-semantic-text-primary)" },
        { slot: "surface.light.destructive.rest.background", token: "var(--cars24-semantic-bg-danger-subtler)" },
        { slot: "surface.light.destructive.rest.border", token: "var(--cars24-semantic-border-danger-subtle)" },
        { slot: "surface.light.destructive.hover.border", token: "var(--cars24-semantic-border-danger-base)" },
        { slot: "surface.light.destructive.foreground", token: "var(--cars24-semantic-text-danger-base)" },
        { slot: "surface.light.disabled.background", token: "var(--cars24-semantic-bg-disabled)" },
        { slot: "surface.light.disabled.foreground", token: "var(--cars24-semantic-text-disabled)" },
        { slot: "surface.dark.solid.rest.background", token: "var(--cars24-semantic-bg-primary)" },
        { slot: "surface.dark.solid.hover.background", token: "var(--cars24-utility-alpha-white-900)" },
        { slot: "surface.dark.solid.foreground", token: "var(--cars24-semantic-text-primary)" },
        { slot: "surface.dark.outline.rest.border", token: "var(--cars24-semantic-border-secondary-inverse)" },
        { slot: "surface.dark.outline.hover.background", token: "var(--cars24-utility-alpha-white-100)" },
        { slot: "surface.dark.outline.foreground", token: "var(--cars24-semantic-text-primary-inverse)" },
        { slot: "surface.dark.ghost.hover.background", token: "var(--cars24-utility-alpha-white-100)" },
        { slot: "surface.dark.ghost.foreground", token: "var(--cars24-semantic-text-primary-inverse)" },
        { slot: "surface.dark.transparent.rest.background", token: "var(--cars24-utility-alpha-white-200)" },
        { slot: "surface.dark.transparent.hover.background", token: "var(--cars24-utility-alpha-white-300)" },
        { slot: "surface.dark.transparent.foreground", token: "var(--cars24-semantic-text-primary-inverse)" },
        { slot: "surface.dark.destructive.rest.background", token: "var(--cars24-semantic-bg-danger-base)" },
        { slot: "surface.dark.destructive.hover.background", token: "var(--cars24-semantic-bg-danger-bold)" },
        { slot: "surface.dark.destructive.foreground", token: "var(--cars24-semantic-text-primary-inverse)" },
        { slot: "surface.dark.disabled.background", token: "var(--cars24-semantic-bg-disabled-inverse)" },
        { slot: "surface.dark.disabled.foreground", token: "var(--cars24-semantic-text-disabled-inverse)" }
      ],
      themeScopes: ["core", "acme"]
    },
    {
      canonicalId: "component.accordion",
      canonicalName: "Accordion",
      layer: "component",
      status: "approved",
      platform: "shared",
      figmaComponentName: "Accordion",
      description:
        "Expandable content container that reveals or hides related information within the same layout.",
      webExport: "@geist/web/canonical/accordion",
      nativeExport: "@geist/native/canonical/accordion",
      variants: [
        { name: "size", values: ["sm", "lg"] },
        { name: "selectionMode", values: ["single", "multiple"] }
      ],
      states: ["default", "hover", "focus", "active", "disabled", "expanded", "collapsed"],
      tokenBindings: [
        { slot: "container.background.rest", token: "var(--cars24-semantic-bg-primary)" },
        { slot: "container.background.hover", token: "var(--cars24-semantic-bg-primary-hover)" },
        { slot: "container.border", token: "var(--cars24-semantic-border-primary)" },
        { slot: "container.focusRing", token: "color.border.focus" },
        { slot: "radius.container.sm", token: "var(--cars24-theme-radius-alt-md)" },
        { slot: "radius.container.lg", token: "var(--cars24-theme-radius-alt-lg)" },
        { slot: "spacing.padding", token: "var(--cars24-misc-gap-16)" },
        { slot: "spacing.headerGap", token: "var(--cars24-misc-gap-12)" },
        { slot: "spacing.sectionGap", token: "var(--cars24-misc-gap-8)" },
        { slot: "spacing.contentGap", token: "var(--cars24-misc-gap-6)" },
        { slot: "spacing.titleGap", token: "var(--cars24-misc-gap-2)" },
        { slot: "icon.size.sm", token: "var(--cars24-misc-size-18)" },
        { slot: "icon.size.lg", token: "var(--cars24-misc-size-20)" },
        { slot: "icon.color.primary", token: "var(--cars24-semantic-icon-primary)" },
        { slot: "icon.color.secondary", token: "var(--cars24-semantic-icon-secondary)" },
        { slot: "content.title.color", token: "var(--cars24-semantic-text-primary)" },
        { slot: "content.supporting.color", token: "var(--cars24-semantic-text-secondary)" },
        { slot: "content.body.color", token: "var(--cars24-semantic-text-secondary)" },
        { slot: "typography.title.fontFamily", token: "var(--cars24-theme-font-family-primary)" },
        { slot: "typography.title.fontWeight", token: "var(--cars24-theme-font-weight-semibold)" },
        { slot: "typography.title.sm", token: "utility/label-2/semibold" },
        { slot: "typography.title.lg", token: "utility/label-1/semibold" },
        { slot: "typography.supporting.fontFamily", token: "var(--cars24-theme-font-family-primary)" },
        { slot: "typography.supporting.fontWeight", token: "var(--cars24-theme-font-weight-regular)" },
        { slot: "typography.supporting.fontSize", token: "var(--cars24-typography-size-utility-label-2)" },
        { slot: "typography.supporting.lineHeight", token: "var(--cars24-typography-line-height-utility-label-2)" },
        { slot: "typography.body", token: "paragraph/body-2" }
      ],
      themeScopes: ["core", "acme"]
    },
    {
      canonicalId: "component.badge",
      canonicalName: "Badge",
      layer: "component",
      status: "approved",
      platform: "shared",
      figmaComponentName: "Badge",
      description: "Compact indicator used to show count, status, or a short state attached to another element.",
      webExport: "@geist/web/canonical/badge",
      nativeExport: "@geist/native/canonical/badge",
      variants: [
        { name: "size", values: ["Extra Small", "Small", "Medium"] },
        {
          name: "type",
          values: ["Drive pink", "Error", "Feature", "Information", "Neutral", "Sky surge", "Success", "Warning"]
        },
        { name: "priority", values: ["High", "Medium", "Low"] },
        { name: "pillShape", values: ["No", "Yes"] }
      ],
      states: ["default", "hover", "focus", "active", "disabled"],
      tokenBindings: [
        { slot: "spacing.gap.xs", token: "var(--cars24-misc-gap-2)" },
        { slot: "spacing.gap.sm", token: "var(--cars24-misc-gap-2)" },
        { slot: "spacing.gap.md", token: "var(--cars24-misc-gap-4)" },
        { slot: "spacing.padding.xs.inline", token: "var(--cars24-misc-gap-4)" },
        { slot: "spacing.padding.xs.inlinePill", token: "var(--cars24-misc-gap-6)" },
        { slot: "spacing.padding.xs.block", token: "var(--cars24-misc-gap-4)" },
        { slot: "spacing.padding.sm.inline", token: "var(--cars24-misc-gap-4)" },
        { slot: "spacing.padding.sm.inlinePill", token: "var(--cars24-misc-gap-8)" },
        { slot: "spacing.padding.sm.block", token: "var(--cars24-misc-gap-4)" },
        { slot: "spacing.padding.md.inline", token: "var(--cars24-misc-gap-8)" },
        { slot: "spacing.padding.md.inlinePill", token: "var(--cars24-misc-gap-10)" },
        { slot: "spacing.padding.md.block", token: "var(--cars24-misc-gap-8)" },
        { slot: "icon.size.xs", token: "var(--cars24-misc-size-12)" },
        { slot: "icon.size.sm", token: "var(--cars24-misc-size-14)" },
        { slot: "icon.size.md", token: "var(--cars24-misc-size-18)" },
        { slot: "radius.square.xs", token: "var(--cars24-theme-radius-alt-xs)" },
        { slot: "radius.square.sm", token: "var(--cars24-theme-radius-alt-sm)" },
        { slot: "radius.square.md", token: "var(--cars24-theme-radius-alt-md)" },
        { slot: "radius.pill", token: "var(--cars24-theme-radius-full)" },
        { slot: "typography.xs", token: "utility/label-4/medium" },
        { slot: "typography.sm", token: "utility/label-3/medium" },
        { slot: "typography.md", token: "utility/label-1/medium" },
        { slot: "color.drivePink.high.background", token: "var(--cars24-primitive-drive-pink-600)" },
        { slot: "color.drivePink.high.text", token: "var(--cars24-semantic-text-primary-inverse)" },
        { slot: "color.drivePink.medium.background", token: "var(--cars24-primitive-drive-pink-50)" },
        { slot: "color.drivePink.medium.text", token: "var(--cars24-primitive-drive-pink-600)" },
        { slot: "color.drivePink.medium.border", token: "var(--cars24-primitive-drive-pink-600)" },
        { slot: "color.drivePink.low.background", token: "var(--cars24-primitive-drive-pink-50)" },
        { slot: "color.drivePink.low.text", token: "var(--cars24-primitive-drive-pink-600)" },
        { slot: "color.error.high.background", token: "var(--cars24-semantic-bg-danger-base)" },
        { slot: "color.error.high.text", token: "var(--cars24-semantic-text-primary-inverse)" },
        { slot: "color.error.medium.background", token: "var(--cars24-semantic-bg-danger-subtler)" },
        { slot: "color.error.medium.text", token: "var(--cars24-semantic-text-danger-base)" },
        { slot: "color.error.medium.border", token: "var(--cars24-semantic-border-danger-base)" },
        { slot: "color.error.low.background", token: "var(--cars24-semantic-bg-danger-subtler)" },
        { slot: "color.error.low.text", token: "var(--cars24-semantic-text-danger-base)" },
        { slot: "color.feature.high.background", token: "var(--cars24-primitive-pop-purple-500)" },
        { slot: "color.feature.high.text", token: "var(--cars24-semantic-text-primary-inverse)" },
        { slot: "color.feature.medium.background", token: "var(--cars24-primitive-pop-purple-50)" },
        { slot: "color.feature.medium.text", token: "var(--cars24-primitive-pop-purple-500)" },
        { slot: "color.feature.medium.border", token: "var(--cars24-primitive-pop-purple-500)" },
        { slot: "color.feature.low.background", token: "var(--cars24-primitive-pop-purple-50)" },
        { slot: "color.feature.low.text", token: "var(--cars24-primitive-pop-purple-500)" },
        { slot: "color.information.high.background", token: "var(--cars24-semantic-bg-info-base)" },
        { slot: "color.information.high.text", token: "var(--cars24-semantic-text-primary-inverse)" },
        { slot: "color.information.medium.background", token: "var(--cars24-semantic-bg-info-subtler)" },
        { slot: "color.information.medium.text", token: "var(--cars24-semantic-text-info-base)" },
        { slot: "color.information.medium.border", token: "var(--cars24-semantic-bg-info-base)" },
        { slot: "color.information.low.background", token: "var(--cars24-semantic-bg-info-subtler)" },
        { slot: "color.information.low.text", token: "var(--cars24-semantic-text-info-base)" },
        { slot: "color.neutral.high.background", token: "var(--cars24-semantic-bg-primary-inverse)" },
        { slot: "color.neutral.high.text", token: "var(--cars24-semantic-text-primary-inverse)" },
        { slot: "color.neutral.medium.background", token: "var(--cars24-semantic-bg-secondary)" },
        { slot: "color.neutral.medium.text", token: "var(--cars24-semantic-text-secondary)" },
        { slot: "color.neutral.medium.border", token: "var(--cars24-semantic-border-tertiary)" },
        { slot: "color.neutral.low.background", token: "var(--cars24-semantic-bg-tertiary)" },
        { slot: "color.neutral.low.text", token: "var(--cars24-semantic-text-secondary)" },
        { slot: "color.skySurge.high.background", token: "var(--cars24-primitive-sky-surge-700)" },
        { slot: "color.skySurge.high.text", token: "var(--cars24-semantic-text-primary-inverse)" },
        { slot: "color.skySurge.medium.background", token: "var(--cars24-primitive-sky-surge-50)" },
        { slot: "color.skySurge.medium.text", token: "var(--cars24-primitive-sky-surge-700)" },
        { slot: "color.skySurge.medium.border", token: "var(--cars24-primitive-sky-surge-700)" },
        { slot: "color.skySurge.low.background", token: "var(--cars24-primitive-sky-surge-100)" },
        { slot: "color.skySurge.low.text", token: "var(--cars24-primitive-sky-surge-700)" },
        { slot: "color.success.high.background", token: "var(--cars24-semantic-bg-success-base)" },
        { slot: "color.success.high.text", token: "var(--cars24-semantic-text-primary-inverse)" },
        { slot: "color.success.medium.background", token: "var(--cars24-semantic-bg-success-subtler)" },
        { slot: "color.success.medium.text", token: "var(--cars24-semantic-text-success-base)" },
        { slot: "color.success.medium.border", token: "var(--cars24-semantic-border-success-base)" },
        { slot: "color.success.low.background", token: "var(--cars24-semantic-bg-success-subtle)" },
        { slot: "color.success.low.text", token: "var(--cars24-semantic-text-success-base)" },
        { slot: "color.warning.high.background", token: "var(--cars24-semantic-bg-warning-base)" },
        { slot: "color.warning.high.text", token: "var(--cars24-semantic-text-primary-inverse)" },
        { slot: "color.warning.medium.background", token: "var(--cars24-semantic-bg-warning-subtler)" },
        { slot: "color.warning.medium.text", token: "var(--cars24-semantic-text-warning-base)" },
        { slot: "color.warning.medium.border", token: "var(--cars24-semantic-border-warning-base)" },
        { slot: "color.warning.low.background", token: "var(--cars24-semantic-bg-warning-subtle)" },
        { slot: "color.warning.low.text", token: "var(--cars24-semantic-text-warning-base)" }
      ],
      themeScopes: ["core", "acme"]
    },
    {
      canonicalId: "component.banner",
      canonicalName: "Banner",
      layer: "component",
      status: "approved",
      platform: "shared",
      figmaComponentName: "Banner",
      description: "Inline notification surface for status messaging with optional icon and action.",
      webExport: "@geist/web/canonical/banner",
      nativeExport: "@geist/native/canonical/banner",
      variants: [
        { name: "theme", values: ["Light", "Dark"] },
        { name: "state", values: ["Warning", "Success", "Error", "Info", "Brand"] },
        { name: "heading", values: ["true", "false"] },
        { name: "icon", values: ["true", "false"] },
        { name: "action", values: ["true", "false"] },
        { name: "actionType", values: ["Text button", "Icon button"] },
        { name: "title", values: ["New Message Alert"] },
        { name: "description", values: ["New message received!"] }
      ],
      states: ["default"],
      tokenBindings: [
        { slot: "container.width", token: "328px" },
        { slot: "container.radius", token: "var(--cars24-theme-radius-alt-lg)" },
        { slot: "container.shadow", token: "drop-shadow/xl" },
        { slot: "container.gap", token: "var(--cars24-misc-gap-none)" },
        { slot: "container.focusRing", token: "color.border.focus" },
        { slot: "content.gap", token: "var(--cars24-misc-gap-8)" },
        { slot: "content.paddingInline", token: "var(--cars24-misc-gap-12)" },
        { slot: "content.paddingBlock", token: "var(--cars24-misc-gap-16)" },
        { slot: "content.title", token: "utility/label-1/medium" },
        { slot: "content.description.sm", token: "paragraph/body-3" },
        { slot: "content.description.md", token: "paragraph/body-2" },
        { slot: "icon.leading.size", token: "var(--cars24-misc-size-20)" },
        { slot: "icon.action.size", token: "var(--cars24-misc-size-24)" },
        { slot: "action.text.radius", token: "var(--cars24-theme-radius-full)" },
        { slot: "action.text.paddingInline", token: "var(--cars24-misc-gap-12)" },
        { slot: "action.text.paddingBlock", token: "var(--cars24-misc-gap-6)" },
        { slot: "action.text.typography", token: "utility/label-3/medium" },
        { slot: "action.focusRing", token: "color.border.focus" },
        { slot: "tone.light.warning.background", token: "var(--cars24-semantic-bg-warning-subtler)" },
        { slot: "tone.light.warning.border", token: "var(--cars24-semantic-border-warning-subtle)" },
        { slot: "tone.light.warning.icon", token: "var(--cars24-semantic-icon-warning-base)" },
        { slot: "tone.light.warning.title", token: "var(--cars24-semantic-text-primary)" },
        { slot: "tone.light.warning.description", token: "var(--cars24-semantic-text-secondary)" },
        { slot: "tone.light.success.background", token: "var(--cars24-semantic-bg-success-subtler)" },
        { slot: "tone.light.success.border", token: "var(--cars24-semantic-border-success-subtle)" },
        { slot: "tone.light.success.icon", token: "var(--cars24-semantic-icon-success-base)" },
        { slot: "tone.light.success.title", token: "var(--cars24-semantic-text-primary)" },
        { slot: "tone.light.success.description", token: "var(--cars24-semantic-text-secondary)" },
        { slot: "tone.light.error.background", token: "var(--cars24-semantic-bg-danger-subtler)" },
        { slot: "tone.light.error.border", token: "var(--cars24-semantic-border-danger-subtle)" },
        { slot: "tone.light.error.icon", token: "var(--cars24-semantic-icon-danger-base)" },
        { slot: "tone.light.error.title", token: "var(--cars24-semantic-text-primary)" },
        { slot: "tone.light.error.description", token: "var(--cars24-semantic-text-secondary)" },
        { slot: "tone.light.info.background", token: "var(--cars24-semantic-bg-info-subtler)" },
        { slot: "tone.light.info.border", token: "var(--cars24-semantic-border-info-subtle)" },
        { slot: "tone.light.info.icon", token: "var(--cars24-semantic-icon-info-base)" },
        { slot: "tone.light.info.title", token: "var(--cars24-semantic-text-primary)" },
        { slot: "tone.light.info.description", token: "var(--cars24-semantic-text-secondary)" },
        { slot: "tone.light.brand.background", token: "var(--cars24-semantic-bg-brand-subtler)" },
        { slot: "tone.light.brand.border", token: "var(--cars24-semantic-border-brand-subtle)" },
        { slot: "tone.light.brand.icon", token: "var(--cars24-semantic-icon-brand-base)" },
        { slot: "tone.light.brand.title", token: "var(--cars24-semantic-text-primary)" },
        { slot: "tone.light.brand.description", token: "var(--cars24-semantic-text-secondary)" },
        { slot: "tone.dark.warning.background", token: "var(--cars24-semantic-bg-warning-base)" },
        { slot: "tone.dark.warning.border", token: "transparent" },
        { slot: "tone.dark.warning.icon", token: "var(--cars24-semantic-icon-primary-inverse)" },
        { slot: "tone.dark.warning.title", token: "var(--cars24-semantic-text-primary-inverse)" },
        { slot: "tone.dark.warning.description", token: "var(--cars24-semantic-text-primary-inverse)" },
        { slot: "tone.dark.success.background", token: "var(--cars24-semantic-bg-success-base)" },
        { slot: "tone.dark.success.border", token: "transparent" },
        { slot: "tone.dark.success.icon", token: "var(--cars24-semantic-icon-primary-inverse)" },
        { slot: "tone.dark.success.title", token: "var(--cars24-semantic-text-primary-inverse)" },
        { slot: "tone.dark.success.description", token: "var(--cars24-semantic-text-primary-inverse)" },
        { slot: "tone.dark.error.background", token: "var(--cars24-semantic-bg-danger-base)" },
        { slot: "tone.dark.error.border", token: "transparent" },
        { slot: "tone.dark.error.icon", token: "var(--cars24-semantic-icon-primary-inverse)" },
        { slot: "tone.dark.error.title", token: "var(--cars24-semantic-text-primary-inverse)" },
        { slot: "tone.dark.error.description", token: "var(--cars24-semantic-text-primary-inverse)" },
        { slot: "tone.dark.info.background", token: "var(--cars24-semantic-bg-info-base)" },
        { slot: "tone.dark.info.border", token: "transparent" },
        { slot: "tone.dark.info.icon", token: "var(--cars24-semantic-icon-primary-inverse)" },
        { slot: "tone.dark.info.title", token: "var(--cars24-semantic-text-primary-inverse)" },
        { slot: "tone.dark.info.description", token: "var(--cars24-semantic-text-primary-inverse)" },
        { slot: "tone.dark.brand.background", token: "var(--cars24-semantic-bg-brand-base)" },
        { slot: "tone.dark.brand.border", token: "transparent" },
        { slot: "tone.dark.brand.icon", token: "var(--cars24-semantic-icon-primary-inverse)" },
        { slot: "tone.dark.brand.title", token: "var(--cars24-semantic-text-primary-inverse)" },
        { slot: "tone.dark.brand.description", token: "var(--cars24-semantic-text-primary-inverse)" },
        { slot: "action.light.background", token: "var(--cars24-semantic-bg-primary-inverse)" },
        { slot: "action.light.text", token: "var(--cars24-semantic-text-primary-inverse)" },
        { slot: "action.light.icon", token: "var(--cars24-semantic-icon-secondary)" },
        { slot: "action.dark.background", token: "var(--cars24-semantic-bg-primary)" },
        { slot: "action.dark.text", token: "var(--cars24-semantic-text-primary)" },
        { slot: "action.dark.icon", token: "var(--cars24-semantic-icon-primary-inverse)" },
        { slot: "action.light.warning.background", token: "var(--cars24-semantic-bg-primary-inverse)" },
        { slot: "action.light.warning.text", token: "var(--cars24-semantic-text-primary-inverse)" },
        { slot: "action.light.warning.icon", token: "var(--cars24-semantic-icon-secondary)" },
        { slot: "action.light.success.background", token: "var(--cars24-semantic-bg-primary-inverse)" },
        { slot: "action.light.success.text", token: "var(--cars24-semantic-text-primary-inverse)" },
        { slot: "action.light.success.icon", token: "var(--cars24-semantic-icon-secondary)" },
        { slot: "action.light.error.background", token: "var(--cars24-semantic-bg-primary-inverse)" },
        { slot: "action.light.error.text", token: "var(--cars24-semantic-text-primary-inverse)" },
        { slot: "action.light.error.icon", token: "var(--cars24-semantic-icon-secondary)" },
        { slot: "action.light.info.background", token: "var(--cars24-semantic-bg-primary-inverse)" },
        { slot: "action.light.info.text", token: "var(--cars24-semantic-text-primary-inverse)" },
        { slot: "action.light.info.icon", token: "var(--cars24-semantic-icon-secondary)" },
        { slot: "action.light.brand.background", token: "var(--cars24-semantic-bg-primary-inverse)" },
        { slot: "action.light.brand.text", token: "var(--cars24-semantic-text-primary-inverse)" },
        { slot: "action.light.brand.icon", token: "var(--cars24-semantic-icon-secondary)" },
        { slot: "action.dark.warning.background", token: "var(--cars24-semantic-bg-primary)" },
        { slot: "action.dark.warning.text", token: "var(--cars24-semantic-text-primary)" },
        { slot: "action.dark.warning.icon", token: "var(--cars24-semantic-icon-primary-inverse)" },
        { slot: "action.dark.success.background", token: "var(--cars24-semantic-bg-primary)" },
        { slot: "action.dark.success.text", token: "var(--cars24-semantic-text-primary)" },
        { slot: "action.dark.success.icon", token: "var(--cars24-semantic-icon-primary-inverse)" },
        { slot: "action.dark.error.background", token: "var(--cars24-semantic-bg-primary)" },
        { slot: "action.dark.error.text", token: "var(--cars24-semantic-text-primary)" },
        { slot: "action.dark.error.icon", token: "var(--cars24-semantic-icon-primary-inverse)" },
        { slot: "action.dark.info.background", token: "var(--cars24-semantic-bg-primary)" },
        { slot: "action.dark.info.text", token: "var(--cars24-semantic-text-primary)" },
        { slot: "action.dark.info.icon", token: "var(--cars24-semantic-icon-primary-inverse)" },
        { slot: "action.dark.brand.background", token: "var(--cars24-semantic-bg-primary)" },
        { slot: "action.dark.brand.text", token: "var(--cars24-semantic-text-primary)" },
        { slot: "action.dark.brand.icon", token: "var(--cars24-semantic-icon-primary-inverse)" }
      ],
      themeScopes: ["core", "acme"]
    }
  ],
  widgets: [
    {
      canonicalId: "widget.auth-card",
      canonicalName: "Auth Card",
      layer: "widget",
      status: "approved",
      platform: "shared",
      description: "Composable authentication surface built from approved components.",
      composition: ["component.button"],
      allowedChildren: ["component.button"]
    }
  ],
  pages: [
    {
      canonicalId: "page.sign-in",
      canonicalName: "Sign In",
      layer: "page",
      status: "approved",
      platform: "shared",
      description: "Login page assembled only from approved widgets and components.",
      composition: ["widget.auth-card"]
    }
  ],
  flows: [
    {
      canonicalId: "flow.authentication",
      canonicalName: "Authentication Flow",
      layer: "flow",
      status: "approved",
      platform: "shared",
      description: "A governed sequence of pages for signing in and recovery.",
      pages: ["page.sign-in"]
    }
  ]
};
