import { governanceRules } from "./governance";
import type { DesignSystemRegistry } from "./types";

export const designSystemRegistry: DesignSystemRegistry = {
  governance: governanceRules,
  components: [
    {
      canonicalId: "component.button",
      canonicalName: "Button",
      layer: "component",
      status: "approved",
      platform: "shared",
      figmaComponentName: "Button",
      description: "Primary canonical action component.",
      webExport: "@geist/web/canonical/button",
      nativeExport: "@geist/native/canonical/button",
      variants: [
        { name: "tone", values: ["primary", "secondary", "ghost"] },
        { name: "size", values: ["sm", "md", "lg"] }
      ],
      states: ["default", "hover", "pressed", "disabled", "loading"],
      tokenBindings: [
        { slot: "container.background.primary", token: "color.brand.primary.600" },
        { slot: "container.background.secondary", token: "color.brand.secondary.600" },
        { slot: "container.background.ghost", token: "color.surface.subtle" },
        { slot: "container.border", token: "color.border.default" },
        { slot: "content.text.primary", token: "color.text.inverse" },
        { slot: "content.text.secondary", token: "color.text.inverse" },
        { slot: "content.text.ghost", token: "color.text.primary" },
        { slot: "radius.container", token: "radius.md" },
        { slot: "spacing.gap", token: "spacing.1" },
        { slot: "spacing.paddingBlock", token: "spacing.2" },
        { slot: "spacing.paddingInline.sm", token: "spacing.3" },
        { slot: "spacing.paddingInline.md", token: "spacing.4" },
        { slot: "spacing.paddingInline.lg", token: "spacing.5" },
        { slot: "typography.fontFamily", token: "typography.fontFamily.sans" },
        { slot: "typography.fontWeight", token: "typography.fontWeight.semibold" },
        { slot: "typography.fontSize.sm", token: "typography.fontSize.sm" },
        { slot: "typography.fontSize.md", token: "typography.fontSize.md" },
        { slot: "typography.fontSize.lg", token: "typography.fontSize.lg" },
        { slot: "typography.lineHeight.sm", token: "typography.lineHeight.sm" },
        { slot: "typography.lineHeight.md", token: "typography.lineHeight.md" },
        { slot: "typography.lineHeight.lg", token: "typography.lineHeight.lg" }
      ],
      themeScopes: ["core", "acme"]
    },
    {
      canonicalId: "component.accordion",
      canonicalName: "Accordion",
      layer: "component",
      status: "approved",
      platform: "shared",
      figmaComponentName: "Accordion",
      description:
        "Expandable content container that reveals or hides related information within the same layout.",
      webExport: "@geist/web/canonical/accordion",
      nativeExport: "@geist/native/canonical/accordion",
      variants: [
        { name: "size", values: ["sm", "lg"] },
        { name: "selectionMode", values: ["single", "multiple"] }
      ],
      states: ["default", "hover", "focus", "active", "disabled", "expanded", "collapsed"],
      tokenBindings: [
        { slot: "container.background.rest", token: "var(--cars24-semantic-bg-primary)" },
        { slot: "container.background.hover", token: "var(--cars24-semantic-bg-primary-hover)" },
        { slot: "container.border", token: "var(--cars24-semantic-border-primary)" },
        { slot: "container.focusRing", token: "color.border.focus" },
        { slot: "radius.container.sm", token: "var(--cars24-theme-radius-alt-md)" },
        { slot: "radius.container.lg", token: "var(--cars24-theme-radius-alt-lg)" },
        { slot: "spacing.padding", token: "var(--cars24-misc-gap-16)" },
        { slot: "spacing.headerGap", token: "var(--cars24-misc-gap-12)" },
        { slot: "spacing.sectionGap", token: "var(--cars24-misc-gap-8)" },
        { slot: "spacing.contentGap", token: "var(--cars24-misc-gap-6)" },
        { slot: "spacing.titleGap", token: "var(--cars24-misc-gap-2)" },
        { slot: "icon.size.sm", token: "var(--cars24-misc-size-18)" },
        { slot: "icon.size.lg", token: "var(--cars24-misc-size-20)" },
        { slot: "icon.color.primary", token: "var(--cars24-semantic-icon-primary)" },
        { slot: "icon.color.secondary", token: "var(--cars24-semantic-icon-secondary)" },
        { slot: "content.title.color", token: "var(--cars24-semantic-text-primary)" },
        { slot: "content.supporting.color", token: "var(--cars24-semantic-text-secondary)" },
        { slot: "content.body.color", token: "var(--cars24-semantic-text-secondary)" },
        { slot: "typography.title.fontFamily", token: "var(--cars24-theme-font-family-primary)" },
        { slot: "typography.title.fontWeight", token: "var(--cars24-theme-font-weight-semibold)" },
        { slot: "typography.title.sm", token: "utility/label-2/semibold" },
        { slot: "typography.title.lg", token: "utility/label-1/semibold" },
        { slot: "typography.supporting.fontFamily", token: "var(--cars24-theme-font-family-primary)" },
        { slot: "typography.supporting.fontWeight", token: "var(--cars24-theme-font-weight-regular)" },
        { slot: "typography.supporting.fontSize", token: "var(--cars24-typography-size-utility-label-2)" },
        { slot: "typography.supporting.lineHeight", token: "var(--cars24-typography-line-height-utility-label-2)" },
        { slot: "typography.body", token: "paragraph/body-2" }
      ],
      themeScopes: ["core", "acme"]
    },
    {
      canonicalId: "component.badge",
      canonicalName: "Badge",
      layer: "component",
      status: "approved",
      platform: "shared",
      figmaComponentName: "Badge",
      description: "Compact indicator used to show count, status, or a short state attached to another element.",
      webExport: "@geist/web/canonical/badge",
      nativeExport: "@geist/native/canonical/badge",
      variants: [
        { name: "size", values: ["Extra Small", "Small", "Medium"] },
        {
          name: "type",
          values: ["Drive pink", "Error", "Feature", "Information", "Neutral", "Sky surge", "Success", "Warning"]
        },
        { name: "priority", values: ["High", "Medium", "Low"] },
        { name: "pillShape", values: ["No", "Yes"] }
      ],
      states: ["default", "hover", "focus", "active", "disabled"],
      tokenBindings: [
        { slot: "spacing.gap.xs", token: "var(--cars24-misc-gap-2)" },
        { slot: "spacing.gap.sm", token: "var(--cars24-misc-gap-2)" },
        { slot: "spacing.gap.md", token: "var(--cars24-misc-gap-4)" },
        { slot: "spacing.padding.xs.inline", token: "var(--cars24-misc-gap-4)" },
        { slot: "spacing.padding.xs.inlinePill", token: "var(--cars24-misc-gap-6)" },
        { slot: "spacing.padding.xs.block", token: "var(--cars24-misc-gap-4)" },
        { slot: "spacing.padding.sm.inline", token: "var(--cars24-misc-gap-4)" },
        { slot: "spacing.padding.sm.inlinePill", token: "var(--cars24-misc-gap-8)" },
        { slot: "spacing.padding.sm.block", token: "var(--cars24-misc-gap-4)" },
        { slot: "spacing.padding.md.inline", token: "var(--cars24-misc-gap-8)" },
        { slot: "spacing.padding.md.inlinePill", token: "var(--cars24-misc-gap-10)" },
        { slot: "spacing.padding.md.block", token: "var(--cars24-misc-gap-8)" },
        { slot: "icon.size.xs", token: "var(--cars24-misc-size-12)" },
        { slot: "icon.size.sm", token: "var(--cars24-misc-size-14)" },
        { slot: "icon.size.md", token: "var(--cars24-misc-size-18)" },
        { slot: "radius.square.xs", token: "var(--cars24-theme-radius-alt-xs)" },
        { slot: "radius.square.sm", token: "var(--cars24-theme-radius-alt-sm)" },
        { slot: "radius.square.md", token: "var(--cars24-theme-radius-alt-md)" },
        { slot: "radius.pill", token: "var(--cars24-theme-radius-full)" },
        { slot: "typography.xs", token: "utility/label-4/medium" },
        { slot: "typography.sm", token: "utility/label-3/medium" },
        { slot: "typography.md", token: "utility/label-1/medium" },
        { slot: "color.drivePink.high.background", token: "var(--cars24-primitive-drive-pink-600)" },
        { slot: "color.drivePink.high.text", token: "var(--cars24-semantic-text-primary-inverse)" },
        { slot: "color.drivePink.medium.background", token: "var(--cars24-primitive-drive-pink-50)" },
        { slot: "color.drivePink.medium.text", token: "var(--cars24-primitive-drive-pink-600)" },
        { slot: "color.drivePink.medium.border", token: "var(--cars24-primitive-drive-pink-600)" },
        { slot: "color.drivePink.low.background", token: "var(--cars24-primitive-drive-pink-50)" },
        { slot: "color.drivePink.low.text", token: "var(--cars24-primitive-drive-pink-600)" },
        { slot: "color.error.high.background", token: "var(--cars24-semantic-bg-danger-base)" },
        { slot: "color.error.high.text", token: "var(--cars24-semantic-text-primary-inverse)" },
        { slot: "color.error.medium.background", token: "var(--cars24-semantic-bg-danger-subtler)" },
        { slot: "color.error.medium.text", token: "var(--cars24-semantic-text-danger-base)" },
        { slot: "color.error.medium.border", token: "var(--cars24-semantic-border-danger-base)" },
        { slot: "color.error.low.background", token: "var(--cars24-semantic-bg-danger-subtler)" },
        { slot: "color.error.low.text", token: "var(--cars24-semantic-text-danger-base)" },
        { slot: "color.feature.high.background", token: "var(--cars24-primitive-pop-purple-500)" },
        { slot: "color.feature.high.text", token: "var(--cars24-semantic-text-primary-inverse)" },
        { slot: "color.feature.medium.background", token: "var(--cars24-primitive-pop-purple-50)" },
        { slot: "color.feature.medium.text", token: "var(--cars24-primitive-pop-purple-500)" },
        { slot: "color.feature.medium.border", token: "var(--cars24-primitive-pop-purple-500)" },
        { slot: "color.feature.low.background", token: "var(--cars24-primitive-pop-purple-50)" },
        { slot: "color.feature.low.text", token: "var(--cars24-primitive-pop-purple-500)" },
        { slot: "color.information.high.background", token: "var(--cars24-semantic-bg-info-base)" },
        { slot: "color.information.high.text", token: "var(--cars24-semantic-text-primary-inverse)" },
        { slot: "color.information.medium.background", token: "var(--cars24-semantic-bg-info-subtler)" },
        { slot: "color.information.medium.text", token: "var(--cars24-semantic-text-info-base)" },
        { slot: "color.information.medium.border", token: "var(--cars24-semantic-bg-info-base)" },
        { slot: "color.information.low.background", token: "var(--cars24-semantic-bg-info-subtler)" },
        { slot: "color.information.low.text", token: "var(--cars24-semantic-text-info-base)" },
        { slot: "color.neutral.high.background", token: "var(--cars24-semantic-bg-primary-inverse)" },
        { slot: "color.neutral.high.text", token: "var(--cars24-semantic-text-primary-inverse)" },
        { slot: "color.neutral.medium.background", token: "var(--cars24-semantic-bg-secondary)" },
        { slot: "color.neutral.medium.text", token: "var(--cars24-semantic-text-secondary)" },
        { slot: "color.neutral.medium.border", token: "var(--cars24-semantic-border-tertiary)" },
        { slot: "color.neutral.low.background", token: "var(--cars24-semantic-bg-tertiary)" },
        { slot: "color.neutral.low.text", token: "var(--cars24-semantic-text-secondary)" },
        { slot: "color.skySurge.high.background", token: "var(--cars24-primitive-sky-surge-700)" },
        { slot: "color.skySurge.high.text", token: "var(--cars24-semantic-text-primary-inverse)" },
        { slot: "color.skySurge.medium.background", token: "var(--cars24-primitive-sky-surge-50)" },
        { slot: "color.skySurge.medium.text", token: "var(--cars24-primitive-sky-surge-700)" },
        { slot: "color.skySurge.medium.border", token: "var(--cars24-primitive-sky-surge-700)" },
        { slot: "color.skySurge.low.background", token: "var(--cars24-primitive-sky-surge-100)" },
        { slot: "color.skySurge.low.text", token: "var(--cars24-primitive-sky-surge-700)" },
        { slot: "color.success.high.background", token: "var(--cars24-semantic-bg-success-base)" },
        { slot: "color.success.high.text", token: "var(--cars24-semantic-text-primary-inverse)" },
        { slot: "color.success.medium.background", token: "var(--cars24-semantic-bg-success-subtler)" },
        { slot: "color.success.medium.text", token: "var(--cars24-semantic-text-success-base)" },
        { slot: "color.success.medium.border", token: "var(--cars24-semantic-border-success-base)" },
        { slot: "color.success.low.background", token: "var(--cars24-semantic-bg-success-subtle)" },
        { slot: "color.success.low.text", token: "var(--cars24-semantic-text-success-base)" },
        { slot: "color.warning.high.background", token: "var(--cars24-semantic-bg-warning-base)" },
        { slot: "color.warning.high.text", token: "var(--cars24-semantic-text-primary-inverse)" },
        { slot: "color.warning.medium.background", token: "var(--cars24-semantic-bg-warning-subtler)" },
        { slot: "color.warning.medium.text", token: "var(--cars24-semantic-text-warning-base)" },
        { slot: "color.warning.medium.border", token: "var(--cars24-semantic-border-warning-base)" },
        { slot: "color.warning.low.background", token: "var(--cars24-semantic-bg-warning-subtle)" },
        { slot: "color.warning.low.text", token: "var(--cars24-semantic-text-warning-base)" }
      ],
      themeScopes: ["core", "acme"]
    }
  ],
  widgets: [
    {
      canonicalId: "widget.auth-card",
      canonicalName: "Auth Card",
      layer: "widget",
      status: "approved",
      platform: "shared",
      description: "Composable authentication surface built from approved components.",
      composition: ["component.button"],
      allowedChildren: ["component.button"]
    }
  ],
  pages: [
    {
      canonicalId: "page.sign-in",
      canonicalName: "Sign In",
      layer: "page",
      status: "approved",
      platform: "shared",
      description: "Login page assembled only from approved widgets and components.",
      composition: ["widget.auth-card"]
    }
  ],
  flows: [
    {
      canonicalId: "flow.authentication",
      canonicalName: "Authentication Flow",
      layer: "flow",
      status: "approved",
      platform: "shared",
      description: "A governed sequence of pages for signing in and recovery.",
      pages: ["page.sign-in"]
    }
  ]
};
