import { governanceRules } from "./governance";
import type { DesignSystemRegistry } from "./types";

export const designSystemRegistry: DesignSystemRegistry = {
  governance: governanceRules,
  components: [
    {
      canonicalId: "component.button",
      canonicalName: "Button",
      layer: "component",
      status: "approved",
      platform: "shared",
      figmaComponentName: "Button",
      description: "Primary canonical action component.",
      webExport: "@geist/web/canonical/button",
      nativeExport: "@geist/native/canonical/button",
      variants: [
        { name: "shape", values: ["Regular", "Pill"] },
        { name: "styleVariant", values: ["Solid", "Outline", "Ghost", "Transparent", "Destructive"] },
        { name: "size", values: ["Extra Small", "Small", "Medium", "Large", "Extra Large"] },
        { name: "onDark", values: ["false", "true"] },
        { name: "loading", values: ["false", "true"] },
        { name: "disabled", values: ["false", "true"] }
      ],
      states: ["rest", "hover", "pressed", "disabled", "loading", "focus"],
      tokenBindings: [
        { slot: "radius.regular.xs", token: "radius.alt.sm" },
        { slot: "radius.regular.sm", token: "radius.alt.sm" },
        { slot: "radius.regular.md", token: "radius.alt.md" },
        { slot: "radius.regular.lg", token: "radius.alt.lg" },
        { slot: "radius.regular.xl", token: "radius.alt.xl" },
        { slot: "radius.pill", token: "radius.pill" },
        { slot: "size.xs.minWidth", token: "90px" },
        { slot: "size.xs.height", token: "28px" },
        { slot: "size.xs.gap", token: "4px" },
        { slot: "size.xs.paddingInline", token: "12px" },
        { slot: "size.xs.paddingBlock", token: "5px" },
        { slot: "size.xs.typography.fontSize", token: "component.button.typography.xs.fontSize" },
        { slot: "size.xs.typography.lineHeight", token: "component.button.typography.xs.lineHeight" },
        { slot: "size.xs.typography.letterSpacing", token: "component.button.typography.xs.letterSpacing" },
        { slot: "size.sm.minWidth", token: "95px" },
        { slot: "size.sm.height", token: "32px" },
        { slot: "size.sm.gap", token: "4px" },
        { slot: "size.sm.paddingInline", token: "12px" },
        { slot: "size.sm.paddingBlock", token: "7px" },
        { slot: "size.sm.typography.fontSize", token: "component.button.typography.sm.fontSize" },
        { slot: "size.sm.typography.lineHeight", token: "component.button.typography.sm.lineHeight" },
        { slot: "size.sm.typography.letterSpacing", token: "component.button.typography.sm.letterSpacing" },
        { slot: "size.md.minWidth", token: "112px" },
        { slot: "size.md.height", token: "40px" },
        { slot: "size.md.gap", token: "6px" },
        { slot: "size.md.paddingInline", token: "14px" },
        { slot: "size.md.paddingBlock", token: "10px" },
        { slot: "size.md.typography.fontSize", token: "component.button.typography.md.fontSize" },
        { slot: "size.md.typography.lineHeight", token: "component.button.typography.md.lineHeight" },
        { slot: "size.md.typography.letterSpacing", token: "component.button.typography.md.letterSpacing" },
        { slot: "size.lg.minWidth", token: "124px" },
        { slot: "size.lg.height", token: "44px" },
        { slot: "size.lg.gap", token: "6px" },
        { slot: "size.lg.paddingInline", token: "16px" },
        { slot: "size.lg.paddingBlock", token: "12px" },
        { slot: "size.lg.typography.fontSize", token: "component.button.typography.lg.fontSize" },
        { slot: "size.lg.typography.lineHeight", token: "component.button.typography.lg.lineHeight" },
        { slot: "size.lg.typography.letterSpacing", token: "component.button.typography.lg.letterSpacing" },
        { slot: "size.xl.minWidth", token: "130px" },
        { slot: "size.xl.height", token: "56px" },
        { slot: "size.xl.gap", token: "6px" },
        { slot: "size.xl.paddingInline", token: "18px" },
        { slot: "size.xl.paddingBlock", token: "18px" },
        { slot: "size.xl.typography.fontSize", token: "component.button.typography.xl.fontSize" },
        { slot: "size.xl.typography.lineHeight", token: "component.button.typography.xl.lineHeight" },
        { slot: "size.xl.typography.letterSpacing", token: "component.button.typography.xl.letterSpacing" },
        { slot: "typography.fontFamily", token: "typography.fontFamily.sans" },
        { slot: "typography.fontWeight", token: "typography.fontWeight.medium" },
        { slot: "focusRing", token: "color.border.focus" },
        { slot: "surface.light.solid.rest.background", token: "color.brand.primary.600" },
        { slot: "surface.light.solid.hover.background", token: "color.brand.primary.700" },
        { slot: "surface.light.solid.foreground", token: "color.text.inverse" },
        { slot: "surface.light.outline.rest.border", token: "color.brand.primary.600" },
        { slot: "surface.light.outline.hover.border", token: "color.brand.primary.700" },
        { slot: "surface.light.outline.hover.background", token: "color.brand.primary.50" },
        { slot: "surface.light.outline.foreground", token: "color.brand.primary.600" },
        { slot: "surface.light.ghost.hover.background", token: "color.brand.primary.50" },
        { slot: "surface.light.ghost.foreground", token: "color.brand.primary.600" },
        { slot: "surface.light.transparent.foreground", token: "color.text.primary" },
        { slot: "surface.light.destructive.foreground", token: "color.status.danger" },
        { slot: "surface.light.disabled.background", token: "color.surface.subtle" },
        { slot: "surface.light.disabled.foreground", token: "color.text.primary" },
        { slot: "surface.dark.solid.rest.background", token: "color.surface.canvas" },
        { slot: "surface.dark.solid.hover.background", token: "color.surface.subtle" },
        { slot: "surface.dark.solid.foreground", token: "color.text.primary" },
        { slot: "surface.dark.outline.rest.border", token: "color.text.inverse" },
        { slot: "surface.dark.outline.foreground", token: "color.text.inverse" },
        { slot: "surface.dark.ghost.foreground", token: "color.text.inverse" },
        { slot: "surface.dark.transparent.foreground", token: "color.text.inverse" },
        { slot: "surface.dark.destructive.rest.background", token: "color.status.danger" },
        { slot: "surface.dark.destructive.foreground", token: "color.text.inverse" },
        { slot: "surface.dark.disabled.foreground", token: "color.text.inverse" }
      ],
      themeScopes: ["cars24", "teambhp", "carinfo", "vehicleinfo"]
    },
    {
      canonicalId: "component.linkButton",
      canonicalName: "Link Button",
      layer: "component",
      status: "approved",
      platform: "shared",
      figmaComponentName: "Link button",
      description: "Inline text action with optional icons and token-driven underline states.",
      webExport: "@geist/web/canonical/link-button",
      nativeExport: "@geist/native/canonical/link-button",
      variants: [
        { name: "tone", values: ["Brand", "Black"] },
        { name: "size", values: ["Extra Small", "Small", "Medium", "Large"] },
        { name: "onDark", values: ["false", "true"] },
        { name: "underline", values: ["false", "true"] },
        { name: "disabled", values: ["false", "true"] }
      ],
      states: ["rest", "hover", "pressed", "focus", "disabled"],
      tokenBindings: [
        { slot: "size.xs.height", token: "component.linkButton.size.xs.height" },
        { slot: "size.xs.gap", token: "component.linkButton.size.xs.gap" },
        { slot: "size.xs.iconSize", token: "component.linkButton.size.xs.iconSize" },
        { slot: "size.xs.typography.fontSize", token: "component.linkButton.typography.xs.fontSize" },
        { slot: "size.xs.typography.lineHeight", token: "component.linkButton.typography.xs.lineHeight" },
        { slot: "size.xs.typography.letterSpacing", token: "component.linkButton.typography.xs.letterSpacing" },
        { slot: "size.sm.height", token: "component.linkButton.size.sm.height" },
        { slot: "size.sm.gap", token: "component.linkButton.size.sm.gap" },
        { slot: "size.sm.iconSize", token: "component.linkButton.size.sm.iconSize" },
        { slot: "size.sm.typography.fontSize", token: "component.linkButton.typography.sm.fontSize" },
        { slot: "size.sm.typography.lineHeight", token: "component.linkButton.typography.sm.lineHeight" },
        { slot: "size.sm.typography.letterSpacing", token: "component.linkButton.typography.sm.letterSpacing" },
        { slot: "size.md.height", token: "component.linkButton.size.md.height" },
        { slot: "size.md.gap", token: "component.linkButton.size.md.gap" },
        { slot: "size.md.iconSize", token: "component.linkButton.size.md.iconSize" },
        { slot: "size.md.typography.fontSize", token: "component.linkButton.typography.md.fontSize" },
        { slot: "size.md.typography.lineHeight", token: "component.linkButton.typography.md.lineHeight" },
        { slot: "size.md.typography.letterSpacing", token: "component.linkButton.typography.md.letterSpacing" },
        { slot: "size.lg.height", token: "component.linkButton.size.lg.height" },
        { slot: "size.lg.gap", token: "component.linkButton.size.lg.gap" },
        { slot: "size.lg.iconSize", token: "component.linkButton.size.lg.iconSize" },
        { slot: "size.lg.typography.fontSize", token: "component.linkButton.typography.lg.fontSize" },
        { slot: "size.lg.typography.lineHeight", token: "component.linkButton.typography.lg.lineHeight" },
        { slot: "size.lg.typography.letterSpacing", token: "component.linkButton.typography.lg.letterSpacing" },
        { slot: "typography.fontFamily", token: "typography.fontFamily.sans" },
        { slot: "typography.fontWeight", token: "typography.fontWeight.medium" },
        { slot: "decoration.underlineThickness", token: "component.linkButton.decoration.underlineThickness" },
        { slot: "focusRing.color", token: "color.border.focus" },
        { slot: "focusRing.width", token: "component.linkButton.focus.outlineWidth" },
        { slot: "focusRing.offset", token: "component.linkButton.focus.outlineOffset" },
        { slot: "surface.light.brand.rest.foreground", token: "component.linkButton.color.light.brand.rest" },
        { slot: "surface.light.brand.hover.foreground", token: "component.linkButton.color.light.brand.hover" },
        { slot: "surface.light.black.rest.foreground", token: "component.linkButton.color.light.black.rest" },
        { slot: "surface.light.black.hover.foreground", token: "component.linkButton.color.light.black.hover" },
        { slot: "surface.light.disabled.foreground", token: "component.linkButton.color.light.disabled" },
        { slot: "surface.dark.brand.rest.foreground", token: "component.linkButton.color.dark.brand.rest" },
        { slot: "surface.dark.brand.hover.foreground", token: "component.linkButton.color.dark.brand.hover" },
        { slot: "surface.dark.black.rest.foreground", token: "component.linkButton.color.dark.black.rest" },
        { slot: "surface.dark.black.hover.foreground", token: "component.linkButton.color.dark.black.hover" },
        { slot: "surface.dark.disabled.foreground", token: "component.linkButton.color.dark.disabled" }
      ],
      themeScopes: ["cars24", "teambhp", "carinfo", "vehicleinfo"]
    },
    {
      canonicalId: "component.phoneInput",
      canonicalName: "Phone Input",
      layer: "component",
      status: "approved",
      platform: "web",
      figmaComponentName: "Phone Input",
      description: "Phone number entry field with country selector prefix, optional helper text, and dismiss action.",
      webExport: "@geist/web/canonical/phone-input",
      nativeExport: "",
      variants: [
        { name: "size", values: ["Small", "Large"] },
        { name: "destructive", values: ["false", "true"] },
        { name: "disabled", values: ["false", "true"] },
        { name: "showAction", values: ["false", "true"] },
        { name: "showLabelInfo", values: ["false", "true"] },
        { name: "showHelperIcon", values: ["false", "true"] }
      ],
      states: ["rest", "hover", "active", "typing", "filled", "disabled", "destructive"],
      tokenBindings: [
        { slot: "size.sm.height", token: "component.phoneInput.size.sm.height" },
        { slot: "size.lg.height", token: "component.phoneInput.size.lg.height" },
        { slot: "size.sm.containerGap", token: "component.phoneInput.size.sm.containerGap" },
        { slot: "size.lg.containerGap", token: "component.phoneInput.size.lg.containerGap" },
        { slot: "field.paddingInline", token: "component.phoneInput.size.sm.fieldPaddingInline" },
        { slot: "field.paddingBlock", token: "component.phoneInput.size.sm.fieldPaddingBlock" },
        { slot: "field.contentGap", token: "component.phoneInput.size.sm.contentGap" },
        { slot: "field.countryCodeWidth", token: "component.phoneInput.size.sm.countryCodeWidth" },
        { slot: "field.actionSize", token: "component.phoneInput.size.sm.actionSize" },
        { slot: "radius.field", token: "radius.alt.lg" },
        { slot: "radius.action", token: "radius.pill" },
        { slot: "border.width", token: "component.phoneInput.border.width" },
        { slot: "typography.label.sm.fontSize", token: "component.phoneInput.typography.label.sm.fontSize" },
        { slot: "typography.label.lg.fontSize", token: "component.phoneInput.typography.label.lg.fontSize" },
        { slot: "typography.input.fontSize", token: "component.phoneInput.typography.input.fontSize" },
        { slot: "typography.helper.fontSize", token: "component.phoneInput.typography.helper.fontSize" },
        { slot: "icon.flagSize", token: "component.phoneInput.icon.flagSize" },
        { slot: "icon.labelInfoSize", token: "component.phoneInput.icon.labelInfoSize" },
        { slot: "icon.helperSize", token: "component.phoneInput.icon.helperSize" },
        { slot: "icon.countryChevronSize", token: "component.phoneInput.icon.countryChevronSize" },
        { slot: "icon.actionSize", token: "component.phoneInput.icon.actionSize" },
        { slot: "color.label.default", token: "component.phoneInput.color.label.default" },
        { slot: "color.label.required", token: "component.phoneInput.color.label.required" },
        { slot: "color.label.info", token: "component.phoneInput.color.label.info" },
        { slot: "color.helper.default.text", token: "component.phoneInput.color.helper.default.text" },
        { slot: "color.helper.default.icon", token: "component.phoneInput.color.helper.default.icon" },
        { slot: "color.helper.destructive.text", token: "component.phoneInput.color.helper.destructive.text" },
        { slot: "color.helper.destructive.icon", token: "component.phoneInput.color.helper.destructive.icon" },
        { slot: "color.field.rest.background", token: "component.phoneInput.color.field.rest.background" },
        { slot: "color.field.rest.border", token: "component.phoneInput.color.field.rest.border" },
        { slot: "color.field.rest.placeholder", token: "component.phoneInput.color.field.rest.placeholder" },
        { slot: "color.field.rest.value", token: "component.phoneInput.color.field.rest.value" },
        { slot: "color.field.rest.countryCode", token: "component.phoneInput.color.field.rest.countryCode" },
        { slot: "color.field.rest.chevron", token: "component.phoneInput.color.field.rest.chevron" },
        { slot: "color.field.rest.actionBorder", token: "component.phoneInput.color.field.rest.actionBorder" },
        { slot: "color.field.rest.actionIcon", token: "component.phoneInput.color.field.rest.actionIcon" },
        { slot: "color.field.hover.background", token: "component.phoneInput.color.field.hover.background" },
        { slot: "color.field.hover.border", token: "component.phoneInput.color.field.hover.border" },
        { slot: "color.field.hover.placeholder", token: "component.phoneInput.color.field.hover.placeholder" },
        { slot: "color.field.hover.value", token: "component.phoneInput.color.field.hover.value" },
        { slot: "color.field.hover.countryCode", token: "component.phoneInput.color.field.hover.countryCode" },
        { slot: "color.field.hover.chevron", token: "component.phoneInput.color.field.hover.chevron" },
        { slot: "color.field.hover.actionBorder", token: "component.phoneInput.color.field.hover.actionBorder" },
        { slot: "color.field.hover.actionIcon", token: "component.phoneInput.color.field.hover.actionIcon" },
        { slot: "color.field.active.background", token: "component.phoneInput.color.field.active.background" },
        { slot: "color.field.active.border", token: "component.phoneInput.color.field.active.border" },
        { slot: "color.field.active.placeholder", token: "component.phoneInput.color.field.active.placeholder" },
        { slot: "color.field.active.value", token: "component.phoneInput.color.field.active.value" },
        { slot: "color.field.active.countryCode", token: "component.phoneInput.color.field.active.countryCode" },
        { slot: "color.field.active.chevron", token: "component.phoneInput.color.field.active.chevron" },
        { slot: "color.field.active.caret", token: "component.phoneInput.color.field.active.caret" },
        { slot: "color.field.active.actionBorder", token: "component.phoneInput.color.field.active.actionBorder" },
        { slot: "color.field.active.actionIcon", token: "component.phoneInput.color.field.active.actionIcon" },
        { slot: "color.field.filled.background", token: "component.phoneInput.color.field.filled.background" },
        { slot: "color.field.filled.border", token: "component.phoneInput.color.field.filled.border" },
        { slot: "color.field.filled.placeholder", token: "component.phoneInput.color.field.filled.placeholder" },
        { slot: "color.field.filled.value", token: "component.phoneInput.color.field.filled.value" },
        { slot: "color.field.filled.countryCode", token: "component.phoneInput.color.field.filled.countryCode" },
        { slot: "color.field.filled.chevron", token: "component.phoneInput.color.field.filled.chevron" },
        { slot: "color.field.filled.actionBorder", token: "component.phoneInput.color.field.filled.actionBorder" },
        { slot: "color.field.filled.actionIcon", token: "component.phoneInput.color.field.filled.actionIcon" },
        { slot: "color.field.destructive.background", token: "component.phoneInput.color.field.destructive.background" },
        { slot: "color.field.destructive.border", token: "component.phoneInput.color.field.destructive.border" },
        { slot: "color.field.destructive.placeholder", token: "component.phoneInput.color.field.destructive.placeholder" },
        { slot: "color.field.destructive.value", token: "component.phoneInput.color.field.destructive.value" },
        { slot: "color.field.destructive.countryCode", token: "component.phoneInput.color.field.destructive.countryCode" },
        { slot: "color.field.destructive.chevron", token: "component.phoneInput.color.field.destructive.chevron" },
        { slot: "color.field.destructive.actionBorder", token: "component.phoneInput.color.field.destructive.actionBorder" },
        { slot: "color.field.destructive.actionIcon", token: "component.phoneInput.color.field.destructive.actionIcon" },
        { slot: "color.field.disabled.background", token: "component.phoneInput.color.field.disabled.background" },
        { slot: "color.field.disabled.border", token: "component.phoneInput.color.field.disabled.border" },
        { slot: "color.field.disabled.placeholder", token: "component.phoneInput.color.field.disabled.placeholder" },
        { slot: "color.field.disabled.value", token: "component.phoneInput.color.field.disabled.value" },
        { slot: "color.field.disabled.countryCode", token: "component.phoneInput.color.field.disabled.countryCode" },
        { slot: "color.field.disabled.chevron", token: "component.phoneInput.color.field.disabled.chevron" },
        { slot: "color.field.disabled.actionBorder", token: "component.phoneInput.color.field.disabled.actionBorder" },
        { slot: "color.field.disabled.actionIcon", token: "component.phoneInput.color.field.disabled.actionIcon" }
      ],
      themeScopes: ["cars24", "teambhp", "carinfo", "vehicleinfo"]
    },
    {
      canonicalId: "component.textInput",
      canonicalName: "Text Input",
      layer: "component",
      status: "approved",
      platform: "web",
      figmaComponentName: "Text Input",
      description:
        "Single-line text entry field with token-driven affix icons, validation feedback, and size-specific label/helper rhythm.",
      webExport: "@geist/web/canonical/text-input",
      nativeExport: "",
      variants: [
        { name: "size", values: ["Small", "Large"] },
        { name: "validationState", values: ["Default", "Error", "Success"] },
        { name: "disabled", values: ["false", "true"] },
        { name: "showLabelInfo", values: ["false", "true"] },
        { name: "showHelperIcon", values: ["false", "true"] },
        { name: "prefixIcon", values: ["false", "true"] },
        { name: "suffixIcon", values: ["false", "true"] }
      ],
      states: ["rest", "hover", "active", "typing", "typed", "error", "success", "disabled"],
      tokenBindings: [
        { slot: "size.sm.height", token: "component.textInput.size.sm.height" },
        { slot: "size.lg.height", token: "component.textInput.size.lg.height" },
        { slot: "size.sm.containerGap", token: "component.textInput.size.sm.containerGap" },
        { slot: "size.lg.containerGap", token: "component.textInput.size.lg.containerGap" },
        { slot: "size.sm.fieldGap", token: "component.textInput.size.sm.fieldGap" },
        { slot: "size.lg.fieldGap", token: "component.textInput.size.lg.fieldGap" },
        { slot: "size.sm.fieldPaddingInline", token: "component.textInput.size.sm.fieldPaddingInline" },
        { slot: "size.lg.fieldPaddingInline", token: "component.textInput.size.lg.fieldPaddingInline" },
        { slot: "size.sm.fieldPaddingBlock", token: "component.textInput.size.sm.fieldPaddingBlock" },
        { slot: "size.lg.fieldPaddingBlock", token: "component.textInput.size.lg.fieldPaddingBlock" },
        { slot: "size.sm.labelPaddingInline", token: "component.textInput.size.sm.labelPaddingInline" },
        { slot: "size.lg.labelPaddingInline", token: "component.textInput.size.lg.labelPaddingInline" },
        { slot: "size.sm.affixBoxSize", token: "component.textInput.size.sm.affixBoxSize" },
        { slot: "size.lg.affixBoxSize", token: "component.textInput.size.lg.affixBoxSize" },
        { slot: "size.sm.helperGap", token: "component.textInput.size.sm.helperGap" },
        { slot: "size.lg.helperGap", token: "component.textInput.size.lg.helperGap" },
        { slot: "radius.sm", token: "radius.alt.md" },
        { slot: "radius.lg", token: "radius.alt.lg" },
        { slot: "border.width", token: "component.textInput.border.width" },
        { slot: "caret.width", token: "component.textInput.caret.width" },
        { slot: "caret.gap", token: "component.textInput.caret.gap" },
        { slot: "icon.affix", token: "component.textInput.icon.affixSize" },
        { slot: "icon.helper", token: "component.textInput.icon.helperSize" },
        { slot: "typography.input.sm.fontSize", token: "component.textInput.typography.input.sm.fontSize" },
        { slot: "typography.input.sm.lineHeight", token: "component.textInput.typography.input.sm.lineHeight" },
        { slot: "typography.input.sm.letterSpacing", token: "component.textInput.typography.input.sm.letterSpacing" },
        { slot: "typography.input.lg.fontSize", token: "component.textInput.typography.input.lg.fontSize" },
        { slot: "typography.input.lg.lineHeight", token: "component.textInput.typography.input.lg.lineHeight" },
        { slot: "typography.input.lg.letterSpacing", token: "component.textInput.typography.input.lg.letterSpacing" },
        { slot: "typography.helper.sm.fontSize", token: "component.textInput.typography.helper.sm.fontSize" },
        { slot: "typography.helper.sm.lineHeight", token: "component.textInput.typography.helper.sm.lineHeight" },
        { slot: "typography.helper.sm.letterSpacing", token: "component.textInput.typography.helper.sm.letterSpacing" },
        { slot: "typography.helper.lg.fontSize", token: "component.textInput.typography.helper.lg.fontSize" },
        { slot: "typography.helper.lg.lineHeight", token: "component.textInput.typography.helper.lg.lineHeight" },
        { slot: "typography.helper.lg.letterSpacing", token: "component.textInput.typography.helper.lg.letterSpacing" },
        { slot: "color.helper.default.text", token: "component.textInput.color.helper.default.text" },
        { slot: "color.helper.default.icon", token: "component.textInput.color.helper.default.icon" },
        { slot: "color.helper.error.text", token: "component.textInput.color.helper.error.text" },
        { slot: "color.helper.error.icon", token: "component.textInput.color.helper.error.icon" },
        { slot: "color.helper.success.text", token: "component.textInput.color.helper.success.text" },
        { slot: "color.helper.success.icon", token: "component.textInput.color.helper.success.icon" },
        { slot: "color.field.rest.background", token: "component.textInput.color.field.rest.background" },
        { slot: "color.field.rest.border", token: "component.textInput.color.field.rest.border" },
        { slot: "color.field.rest.placeholder", token: "component.textInput.color.field.rest.placeholder" },
        { slot: "color.field.rest.value", token: "component.textInput.color.field.rest.value" },
        { slot: "color.field.rest.affix", token: "component.textInput.color.field.rest.affix" },
        { slot: "color.field.hover.background", token: "component.textInput.color.field.hover.background" },
        { slot: "color.field.hover.border", token: "component.textInput.color.field.hover.border" },
        { slot: "color.field.hover.placeholder", token: "component.textInput.color.field.hover.placeholder" },
        { slot: "color.field.hover.value", token: "component.textInput.color.field.hover.value" },
        { slot: "color.field.hover.affix", token: "component.textInput.color.field.hover.affix" },
        { slot: "color.field.active.background", token: "component.textInput.color.field.active.background" },
        { slot: "color.field.active.border", token: "component.textInput.color.field.active.border" },
        { slot: "color.field.active.placeholder", token: "component.textInput.color.field.active.placeholder" },
        { slot: "color.field.active.value", token: "component.textInput.color.field.active.value" },
        { slot: "color.field.active.affix", token: "component.textInput.color.field.active.affix" },
        { slot: "color.field.typed.background", token: "component.textInput.color.field.typed.background" },
        { slot: "color.field.typed.border", token: "component.textInput.color.field.typed.border" },
        { slot: "color.field.typed.placeholder", token: "component.textInput.color.field.typed.placeholder" },
        { slot: "color.field.typed.value", token: "component.textInput.color.field.typed.value" },
        { slot: "color.field.typed.affix", token: "component.textInput.color.field.typed.affix" },
        { slot: "color.field.error.background", token: "component.textInput.color.field.error.background" },
        { slot: "color.field.error.border", token: "component.textInput.color.field.error.border" },
        { slot: "color.field.error.placeholder", token: "component.textInput.color.field.error.placeholder" },
        { slot: "color.field.error.value", token: "component.textInput.color.field.error.value" },
        { slot: "color.field.error.affix", token: "component.textInput.color.field.error.affix" },
        { slot: "color.field.success.background", token: "component.textInput.color.field.success.background" },
        { slot: "color.field.success.border", token: "component.textInput.color.field.success.border" },
        { slot: "color.field.success.placeholder", token: "component.textInput.color.field.success.placeholder" },
        { slot: "color.field.success.value", token: "component.textInput.color.field.success.value" },
        { slot: "color.field.success.affix", token: "component.textInput.color.field.success.affix" },
        { slot: "color.field.disabled.background", token: "component.textInput.color.field.disabled.background" },
        { slot: "color.field.disabled.border", token: "component.textInput.color.field.disabled.border" },
        { slot: "color.field.disabled.placeholder", token: "component.textInput.color.field.disabled.placeholder" },
        { slot: "color.field.disabled.value", token: "component.textInput.color.field.disabled.value" },
        { slot: "color.field.disabled.affix", token: "component.textInput.color.field.disabled.affix" }
      ],
      themeScopes: ["cars24", "teambhp", "carinfo", "vehicleinfo"]
    },
    {
      canonicalId: "component.label",
      canonicalName: "Label",
      layer: "component",
      status: "approved",
      platform: "web",
      figmaComponentName: "Label",
      description:
        "Reusable field label with token-driven size-specific typography, supporting text, required marker, and info affordance.",
      webExport: "@geist/web/canonical/label",
      nativeExport: "",
      variants: [
        { name: "size", values: ["Extra Small", "Small", "Medium", "Large"] },
        { name: "required", values: ["false", "true"] },
        { name: "showInfoIcon", values: ["false", "true"] },
        { name: "description", values: ["false", "true"] }
      ],
      states: ["default"],
      tokenBindings: [
        { slot: "spacing.stack.xs", token: "component.label.xs.stackGap" },
        { slot: "spacing.stack.sm", token: "component.label.sm.stackGap" },
        { slot: "spacing.stack.md", token: "component.label.md.stackGap" },
        { slot: "spacing.stack.lg", token: "component.label.lg.stackGap" },
        { slot: "spacing.slot.xs", token: "component.label.xs.slotGap" },
        { slot: "spacing.slot.sm", token: "component.label.sm.slotGap" },
        { slot: "spacing.slot.md", token: "component.label.md.slotGap" },
        { slot: "spacing.slot.lg", token: "component.label.lg.slotGap" },
        { slot: "icon.info.xs", token: "component.label.xs.iconSize" },
        { slot: "icon.info.sm", token: "component.label.sm.iconSize" },
        { slot: "icon.info.md", token: "component.label.md.iconSize" },
        { slot: "icon.info.lg", token: "component.label.lg.iconSize" },
        { slot: "typography.label.xs", token: "utility/label-4/medium" },
        { slot: "typography.label.sm", token: "utility/label-3/medium" },
        { slot: "typography.label.md", token: "utility/label-2/medium" },
        { slot: "typography.label.lg", token: "utility/label-1/medium" },
        { slot: "typography.description.xs", token: "utility/fine-print/sm" },
        { slot: "typography.description.sm", token: "paragraph/body-3" },
        { slot: "typography.description.md", token: "paragraph/body-3" },
        { slot: "typography.description.lg", token: "paragraph/body-3" },
        { slot: "color.label", token: "component.phoneInput.color.label.default" },
        { slot: "color.required", token: "component.phoneInput.color.label.required" },
        { slot: "color.info", token: "component.phoneInput.color.label.info" },
        { slot: "color.description", token: "component.phoneInput.color.helper.default.text" }
      ],
      themeScopes: ["cars24", "teambhp", "carinfo", "vehicleinfo"]
    },
    {
      canonicalId: "component.captionButton",
      canonicalName: "Caption Button",
      layer: "component",
      status: "approved",
      platform: "shared",
      figmaComponentName: "Caption Button",
      description: "Action button with a stacked supporting caption placed above or below the primary label.",
      webExport: "@geist/web/canonical/caption-button",
      nativeExport: "@geist/native/canonical/caption-button",
      variants: [
        { name: "styleVariant", values: ["Primary", "Secondary"] },
        { name: "size", values: ["Medium", "Large"] },
        { name: "captionPosition", values: ["Up", "Down"] },
        { name: "disabled", values: ["false", "true"] }
      ],
      states: ["rest", "hover", "pressed", "focus", "disabled"],
      tokenBindings: [
        { slot: "size.md.height", token: "component.captionButton.size.md.height" },
        { slot: "size.md.paddingInline", token: "component.captionButton.size.md.paddingInline" },
        { slot: "size.md.borderRadius", token: "component.captionButton.size.md.borderRadius" },
        { slot: "size.lg.height", token: "component.captionButton.size.lg.height" },
        { slot: "size.lg.paddingInline", token: "component.captionButton.size.lg.paddingInline" },
        { slot: "size.lg.borderRadius", token: "component.captionButton.size.lg.borderRadius" },
        { slot: "typography.label.md.fontSize", token: "component.captionButton.typography.label.md.fontSize" },
        { slot: "typography.label.md.lineHeight", token: "component.captionButton.typography.label.md.lineHeight" },
        { slot: "typography.label.md.letterSpacing", token: "component.captionButton.typography.label.md.letterSpacing" },
        { slot: "typography.label.lg.fontSize", token: "component.captionButton.typography.label.lg.fontSize" },
        { slot: "typography.label.lg.lineHeight", token: "component.captionButton.typography.label.lg.lineHeight" },
        { slot: "typography.label.lg.letterSpacing", token: "component.captionButton.typography.label.lg.letterSpacing" },
        { slot: "typography.caption.md.fontSize", token: "component.captionButton.typography.caption.md.fontSize" },
        { slot: "typography.caption.md.lineHeight", token: "component.captionButton.typography.caption.md.lineHeight" },
        { slot: "typography.caption.md.letterSpacing", token: "component.captionButton.typography.caption.md.letterSpacing" },
        { slot: "typography.caption.lg.fontSize", token: "component.captionButton.typography.caption.lg.fontSize" },
        { slot: "typography.caption.lg.lineHeight", token: "component.captionButton.typography.caption.lg.lineHeight" },
        { slot: "typography.caption.lg.letterSpacing", token: "component.captionButton.typography.caption.lg.letterSpacing" },
        { slot: "typography.fontFamily", token: "typography.fontFamily.sans" },
        { slot: "typography.fontWeight.label", token: "typography.fontWeight.medium" },
        { slot: "typography.fontWeight.caption", token: "typography.fontWeight.regular" },
        { slot: "border.width", token: "component.captionButton.border.width" },
        { slot: "focusRing.color", token: "color.border.focus" },
        { slot: "focusRing.width", token: "component.captionButton.focus.outlineWidth" },
        { slot: "focusRing.offset", token: "component.captionButton.focus.outlineOffset" },
        {
          slot: "surface.light.primary.rest.background",
          token: "component.captionButton.color.light.primary.rest.background"
        },
        {
          slot: "surface.light.primary.rest.foreground",
          token: "component.captionButton.color.light.primary.rest.foreground"
        },
        {
          slot: "surface.light.primary.hover.background",
          token: "component.captionButton.color.light.primary.hover.background"
        },
        {
          slot: "surface.light.primary.hover.foreground",
          token: "component.captionButton.color.light.primary.hover.foreground"
        },
        {
          slot: "surface.light.secondary.rest.background",
          token: "component.captionButton.color.light.secondary.rest.background"
        },
        {
          slot: "surface.light.secondary.rest.border",
          token: "component.captionButton.color.light.secondary.rest.border"
        },
        {
          slot: "surface.light.secondary.rest.foreground",
          token: "component.captionButton.color.light.secondary.rest.foreground"
        },
        {
          slot: "surface.light.secondary.hover.background",
          token: "component.captionButton.color.light.secondary.hover.background"
        },
        {
          slot: "surface.light.secondary.hover.border",
          token: "component.captionButton.color.light.secondary.hover.border"
        },
        {
          slot: "surface.light.secondary.hover.foreground",
          token: "component.captionButton.color.light.secondary.hover.foreground"
        },
        {
          slot: "surface.light.disabled.background",
          token: "component.captionButton.color.light.disabled.background"
        },
        {
          slot: "surface.light.disabled.border",
          token: "component.captionButton.color.light.disabled.border"
        },
        {
          slot: "surface.light.disabled.foreground",
          token: "component.captionButton.color.light.disabled.foreground"
        }
      ],
      themeScopes: ["cars24", "teambhp", "carinfo", "vehicleinfo"]
    },
    {
      canonicalId: "component.socialButton",
      canonicalName: "Social Button",
      layer: "component",
      status: "approved",
      platform: "shared",
      figmaComponentName: "SocialButton",
      description: "Neutral social sign-in button with provider icon, light-surface hover state, and token-driven sizing.",
      webExport: "@geist/web/canonical/social-button",
      nativeExport: "@geist/native/canonical/social-button",
      variants: [
        { name: "size", values: ["Medium", "Large"] },
        { name: "disabled", values: ["false", "true"] }
      ],
      states: ["rest", "hover", "pressed", "focus", "disabled"],
      tokenBindings: [
        { slot: "size.md.height", token: "component.socialButton.size.md.height" },
        { slot: "size.md.gap", token: "component.socialButton.size.md.gap" },
        { slot: "size.md.paddingInline", token: "component.socialButton.size.md.paddingInline" },
        { slot: "size.md.iconSize", token: "component.socialButton.size.md.iconSize" },
        { slot: "size.md.borderRadius", token: "radius.alt.md" },
        { slot: "size.lg.height", token: "component.socialButton.size.lg.height" },
        { slot: "size.lg.gap", token: "component.socialButton.size.lg.gap" },
        { slot: "size.lg.paddingInline", token: "component.socialButton.size.lg.paddingInline" },
        { slot: "size.lg.iconSize", token: "component.socialButton.size.lg.iconSize" },
        { slot: "size.lg.borderRadius", token: "radius.alt.lg" },
        { slot: "typography.md.fontSize", token: "component.socialButton.typography.md.fontSize" },
        { slot: "typography.md.lineHeight", token: "component.socialButton.typography.md.lineHeight" },
        { slot: "typography.md.letterSpacing", token: "component.socialButton.typography.md.letterSpacing" },
        { slot: "typography.lg.fontSize", token: "component.socialButton.typography.lg.fontSize" },
        { slot: "typography.lg.lineHeight", token: "component.socialButton.typography.lg.lineHeight" },
        { slot: "typography.lg.letterSpacing", token: "component.socialButton.typography.lg.letterSpacing" },
        { slot: "typography.fontFamily", token: "typography.fontFamily.sans" },
        { slot: "typography.fontWeight", token: "typography.fontWeight.medium" },
        { slot: "border.width", token: "component.socialButton.border.width" },
        { slot: "focusRing.color", token: "color.border.focus" },
        { slot: "focusRing.width", token: "component.socialButton.focus.outlineWidth" },
        { slot: "focusRing.offset", token: "component.socialButton.focus.outlineOffset" },
        { slot: "surface.light.rest.background", token: "component.socialButton.color.light.rest.background" },
        { slot: "surface.light.rest.border", token: "component.socialButton.color.light.rest.border" },
        { slot: "surface.light.rest.foreground", token: "component.socialButton.color.light.rest.foreground" },
        { slot: "surface.light.rest.icon", token: "component.socialButton.color.light.rest.icon" },
        { slot: "surface.light.hover.background", token: "component.socialButton.color.light.hover.background" },
        { slot: "surface.light.hover.border", token: "component.socialButton.color.light.hover.border" },
        { slot: "surface.light.hover.foreground", token: "component.socialButton.color.light.hover.foreground" },
        { slot: "surface.light.hover.icon", token: "component.socialButton.color.light.hover.icon" },
        { slot: "surface.light.disabled.background", token: "component.socialButton.color.light.disabled.background" },
        { slot: "surface.light.disabled.border", token: "component.socialButton.color.light.disabled.border" },
        { slot: "surface.light.disabled.foreground", token: "component.socialButton.color.light.disabled.foreground" },
        { slot: "surface.light.disabled.icon", token: "component.socialButton.color.light.disabled.icon" }
      ],
      themeScopes: ["cars24", "teambhp", "carinfo", "vehicleinfo"]
    },
    {
      canonicalId: "component.backToTopButton",
      canonicalName: "Back to Top Button",
      layer: "component",
      status: "approved",
      platform: "shared",
      figmaComponentName: "Back to top",
      description: "Compact pill-shaped action used to jump back to the top of a page, with light and inverse surfaces.",
      webExport: "@geist/web/canonical/back-to-top-button",
      nativeExport: "@geist/native/canonical/back-to-top-button",
      variants: [
        { name: "inverse", values: ["false", "true"] },
        { name: "icon", values: ["false", "true"] },
        { name: "disabled", values: ["false", "true"] }
      ],
      states: ["rest", "hover", "pressed", "focus", "disabled"],
      tokenBindings: [
        { slot: "size.md.height", token: "component.backToTopButton.size.md.height" },
        { slot: "size.md.gap", token: "component.backToTopButton.size.md.gap" },
        { slot: "size.md.paddingInline", token: "component.backToTopButton.size.md.paddingInline" },
        { slot: "size.md.paddingBlock", token: "component.backToTopButton.size.md.paddingBlock" },
        { slot: "size.md.iconSize", token: "component.backToTopButton.size.md.iconSize" },
        { slot: "typography.md.fontSize", token: "component.backToTopButton.typography.md.fontSize" },
        { slot: "typography.md.lineHeight", token: "component.backToTopButton.typography.md.lineHeight" },
        { slot: "typography.md.letterSpacing", token: "component.backToTopButton.typography.md.letterSpacing" },
        { slot: "typography.fontFamily", token: "typography.fontFamily.sans" },
        { slot: "typography.fontWeight", token: "typography.fontWeight.semibold" },
        { slot: "container.radius", token: "radius.pill" },
        { slot: "container.shadow", token: "drop-shadow/lg" },
        { slot: "border.width", token: "component.backToTopButton.border.width" },
        { slot: "focusRing.color", token: "color.border.focus" },
        { slot: "focusRing.width", token: "component.backToTopButton.focus.outlineWidth" },
        { slot: "focusRing.offset", token: "component.backToTopButton.focus.outlineOffset" },
        { slot: "surface.light.rest.background", token: "component.backToTopButton.color.light.rest.background" },
        { slot: "surface.light.rest.border", token: "component.backToTopButton.color.light.rest.border" },
        { slot: "surface.light.rest.foreground", token: "component.backToTopButton.color.light.rest.foreground" },
        { slot: "surface.light.rest.icon", token: "component.backToTopButton.color.light.rest.icon" },
        { slot: "surface.light.hover.background", token: "component.backToTopButton.color.light.hover.background" },
        { slot: "surface.light.hover.border", token: "component.backToTopButton.color.light.hover.border" },
        { slot: "surface.light.hover.foreground", token: "component.backToTopButton.color.light.hover.foreground" },
        { slot: "surface.light.hover.icon", token: "component.backToTopButton.color.light.hover.icon" },
        { slot: "surface.light.disabled.background", token: "component.backToTopButton.color.light.disabled.background" },
        { slot: "surface.light.disabled.border", token: "component.backToTopButton.color.light.disabled.border" },
        { slot: "surface.light.disabled.foreground", token: "component.backToTopButton.color.light.disabled.foreground" },
        { slot: "surface.light.disabled.icon", token: "component.backToTopButton.color.light.disabled.icon" },
        { slot: "surface.dark.rest.background", token: "component.backToTopButton.color.dark.rest.background" },
        { slot: "surface.dark.rest.border", token: "component.backToTopButton.color.dark.rest.border" },
        { slot: "surface.dark.rest.foreground", token: "component.backToTopButton.color.dark.rest.foreground" },
        { slot: "surface.dark.rest.icon", token: "component.backToTopButton.color.dark.rest.icon" },
        { slot: "surface.dark.hover.background", token: "component.backToTopButton.color.dark.hover.background" },
        { slot: "surface.dark.hover.border", token: "component.backToTopButton.color.dark.hover.border" },
        { slot: "surface.dark.hover.foreground", token: "component.backToTopButton.color.dark.hover.foreground" },
        { slot: "surface.dark.hover.icon", token: "component.backToTopButton.color.dark.hover.icon" },
        { slot: "surface.dark.disabled.background", token: "component.backToTopButton.color.dark.disabled.background" },
        { slot: "surface.dark.disabled.border", token: "component.backToTopButton.color.dark.disabled.border" },
        { slot: "surface.dark.disabled.foreground", token: "component.backToTopButton.color.dark.disabled.foreground" },
        { slot: "surface.dark.disabled.icon", token: "component.backToTopButton.color.dark.disabled.icon" }
      ],
      themeScopes: ["cars24", "teambhp", "carinfo", "vehicleinfo"]
    },
    {
      canonicalId: "component.iconButton",
      canonicalName: "Icon Button",
      layer: "component",
      status: "approved",
      platform: "shared",
      figmaComponentName: "Icon Button",
      description: "Compact icon-only action button with square or circular shape across light and on-dark surfaces.",
      webExport: "@geist/web/canonical/icon-button",
      nativeExport: "@geist/native/canonical/icon-button",
      variants: [
        { name: "shape", values: ["Regular", "Round"] },
        { name: "styleVariant", values: ["Solid - Primary", "Solid - Black", "Outline - Primary", "Outline - Black", "Subtle - Primary", "Subtle - Black", "Ghost - Brand", "Ghost - Black", "Transparent"] },
        { name: "size", values: ["XXXSmall", "XXSmall", "XSmall", "Small", "Medium", "Large"] },
        { name: "onDark", values: ["false", "true"] },
        { name: "disabled", values: ["false", "true"] }
      ],
      states: ["rest", "hover", "pressed", "focus", "disabled"],
      tokenBindings: [
        { slot: "radius.round", token: "radius.pill" },
        { slot: "size.xxxs.boxSize", token: "component.iconButton.size.xxxs.boxSize" },
        { slot: "size.xxxs.iconSize", token: "component.iconButton.size.xxxs.iconSize" },
        { slot: "size.xxxs.borderRadius", token: "component.iconButton.size.xxxs.borderRadius" },
        { slot: "size.xxs.boxSize", token: "component.iconButton.size.xxs.boxSize" },
        { slot: "size.xxs.iconSize", token: "component.iconButton.size.xxs.iconSize" },
        { slot: "size.xxs.borderRadius", token: "component.iconButton.size.xxs.borderRadius" },
        { slot: "size.xs.boxSize", token: "component.iconButton.size.xs.boxSize" },
        { slot: "size.xs.iconSize", token: "component.iconButton.size.xs.iconSize" },
        { slot: "size.xs.borderRadius", token: "component.iconButton.size.xs.borderRadius" },
        { slot: "size.sm.boxSize", token: "component.iconButton.size.sm.boxSize" },
        { slot: "size.sm.iconSize", token: "component.iconButton.size.sm.iconSize" },
        { slot: "size.sm.borderRadius", token: "component.iconButton.size.sm.borderRadius" },
        { slot: "size.md.boxSize", token: "component.iconButton.size.md.boxSize" },
        { slot: "size.md.iconSize", token: "component.iconButton.size.md.iconSize" },
        { slot: "size.md.borderRadius", token: "component.iconButton.size.md.borderRadius" },
        { slot: "size.lg.boxSize", token: "component.iconButton.size.lg.boxSize" },
        { slot: "size.lg.iconSize", token: "component.iconButton.size.lg.iconSize" },
        { slot: "size.lg.borderRadius", token: "component.iconButton.size.lg.borderRadius" },
        { slot: "border.width", token: "component.iconButton.border.width" },
        { slot: "focusRing.color", token: "color.border.focus" },
        { slot: "focusRing.width", token: "component.iconButton.focus.outlineWidth" },
        { slot: "focusRing.offset", token: "component.iconButton.focus.outlineOffset" },
        { slot: "surface.light.solid.primary.rest.background", token: "component.iconButton.color.light.solid.primary.rest.background" },
        { slot: "surface.light.solid.primary.rest.foreground", token: "component.iconButton.color.light.solid.primary.rest.foreground" },
        { slot: "surface.light.solid.primary.hover.background", token: "component.iconButton.color.light.solid.primary.hover.background" },
        { slot: "surface.light.solid.primary.hover.foreground", token: "component.iconButton.color.light.solid.primary.hover.foreground" },
        { slot: "surface.light.solid.black.rest.background", token: "component.iconButton.color.light.solid.black.rest.background" },
        { slot: "surface.light.solid.black.rest.foreground", token: "component.iconButton.color.light.solid.black.rest.foreground" },
        { slot: "surface.light.solid.black.hover.background", token: "component.iconButton.color.light.solid.black.hover.background" },
        { slot: "surface.light.solid.black.hover.foreground", token: "component.iconButton.color.light.solid.black.hover.foreground" },
        { slot: "surface.light.outline.primary.rest.background", token: "component.iconButton.color.light.outline.primary.rest.background" },
        { slot: "surface.light.outline.primary.rest.border", token: "component.iconButton.color.light.outline.primary.rest.border" },
        { slot: "surface.light.outline.primary.rest.foreground", token: "component.iconButton.color.light.outline.primary.rest.foreground" },
        { slot: "surface.light.outline.primary.hover.background", token: "component.iconButton.color.light.outline.primary.hover.background" },
        { slot: "surface.light.outline.primary.hover.border", token: "component.iconButton.color.light.outline.primary.hover.border" },
        { slot: "surface.light.outline.primary.hover.foreground", token: "component.iconButton.color.light.outline.primary.hover.foreground" },
        { slot: "surface.light.outline.black.rest.background", token: "component.iconButton.color.light.outline.black.rest.background" },
        { slot: "surface.light.outline.black.rest.border", token: "component.iconButton.color.light.outline.black.rest.border" },
        { slot: "surface.light.outline.black.rest.foreground", token: "component.iconButton.color.light.outline.black.rest.foreground" },
        { slot: "surface.light.outline.black.hover.background", token: "component.iconButton.color.light.outline.black.hover.background" },
        { slot: "surface.light.outline.black.hover.border", token: "component.iconButton.color.light.outline.black.hover.border" },
        { slot: "surface.light.outline.black.hover.foreground", token: "component.iconButton.color.light.outline.black.hover.foreground" },
        { slot: "surface.light.subtle.primary.rest.background", token: "component.iconButton.color.light.subtle.primary.rest.background" },
        { slot: "surface.light.subtle.primary.rest.foreground", token: "component.iconButton.color.light.subtle.primary.rest.foreground" },
        { slot: "surface.light.subtle.primary.hover.background", token: "component.iconButton.color.light.subtle.primary.hover.background" },
        { slot: "surface.light.subtle.primary.hover.foreground", token: "component.iconButton.color.light.subtle.primary.hover.foreground" },
        { slot: "surface.light.subtle.black.rest.background", token: "component.iconButton.color.light.subtle.black.rest.background" },
        { slot: "surface.light.subtle.black.rest.foreground", token: "component.iconButton.color.light.subtle.black.rest.foreground" },
        { slot: "surface.light.subtle.black.hover.background", token: "component.iconButton.color.light.subtle.black.hover.background" },
        { slot: "surface.light.subtle.black.hover.foreground", token: "component.iconButton.color.light.subtle.black.hover.foreground" },
        { slot: "surface.light.ghost.primary.rest.background", token: "component.iconButton.color.light.ghost.primary.rest.background" },
        { slot: "surface.light.ghost.primary.rest.foreground", token: "component.iconButton.color.light.ghost.primary.rest.foreground" },
        { slot: "surface.light.ghost.primary.hover.background", token: "component.iconButton.color.light.ghost.primary.hover.background" },
        { slot: "surface.light.ghost.primary.hover.foreground", token: "component.iconButton.color.light.ghost.primary.hover.foreground" },
        { slot: "surface.light.ghost.black.rest.background", token: "component.iconButton.color.light.ghost.black.rest.background" },
        { slot: "surface.light.ghost.black.rest.foreground", token: "component.iconButton.color.light.ghost.black.rest.foreground" },
        { slot: "surface.light.ghost.black.hover.background", token: "component.iconButton.color.light.ghost.black.hover.background" },
        { slot: "surface.light.ghost.black.hover.foreground", token: "component.iconButton.color.light.ghost.black.hover.foreground" },
        { slot: "surface.light.transparent.rest.background", token: "component.iconButton.color.light.transparent.rest.background" },
        { slot: "surface.light.transparent.rest.foreground", token: "component.iconButton.color.light.transparent.rest.foreground" },
        { slot: "surface.light.transparent.hover.background", token: "component.iconButton.color.light.transparent.hover.background" },
        { slot: "surface.light.transparent.hover.foreground", token: "component.iconButton.color.light.transparent.hover.foreground" },
        { slot: "surface.light.disabled.background", token: "component.iconButton.color.light.disabled.background" },
        { slot: "surface.light.disabled.border", token: "component.iconButton.color.light.disabled.border" },
        { slot: "surface.light.disabled.foreground", token: "component.iconButton.color.light.disabled.foreground" },
        { slot: "surface.dark.solid.primary.rest.background", token: "component.iconButton.color.dark.solid.primary.rest.background" },
        { slot: "surface.dark.solid.primary.rest.foreground", token: "component.iconButton.color.dark.solid.primary.rest.foreground" },
        { slot: "surface.dark.solid.primary.hover.background", token: "component.iconButton.color.dark.solid.primary.hover.background" },
        { slot: "surface.dark.solid.primary.hover.foreground", token: "component.iconButton.color.dark.solid.primary.hover.foreground" },
        { slot: "surface.dark.solid.black.rest.background", token: "component.iconButton.color.dark.solid.black.rest.background" },
        { slot: "surface.dark.solid.black.rest.foreground", token: "component.iconButton.color.dark.solid.black.rest.foreground" },
        { slot: "surface.dark.solid.black.hover.background", token: "component.iconButton.color.dark.solid.black.hover.background" },
        { slot: "surface.dark.solid.black.hover.foreground", token: "component.iconButton.color.dark.solid.black.hover.foreground" },
        { slot: "surface.dark.outline.primary.rest.background", token: "component.iconButton.color.dark.outline.primary.rest.background" },
        { slot: "surface.dark.outline.primary.rest.border", token: "component.iconButton.color.dark.outline.primary.rest.border" },
        { slot: "surface.dark.outline.primary.rest.foreground", token: "component.iconButton.color.dark.outline.primary.rest.foreground" },
        { slot: "surface.dark.outline.primary.hover.background", token: "component.iconButton.color.dark.outline.primary.hover.background" },
        { slot: "surface.dark.outline.primary.hover.border", token: "component.iconButton.color.dark.outline.primary.hover.border" },
        { slot: "surface.dark.outline.primary.hover.foreground", token: "component.iconButton.color.dark.outline.primary.hover.foreground" },
        { slot: "surface.dark.outline.black.rest.background", token: "component.iconButton.color.dark.outline.black.rest.background" },
        { slot: "surface.dark.outline.black.rest.border", token: "component.iconButton.color.dark.outline.black.rest.border" },
        { slot: "surface.dark.outline.black.rest.foreground", token: "component.iconButton.color.dark.outline.black.rest.foreground" },
        { slot: "surface.dark.outline.black.hover.background", token: "component.iconButton.color.dark.outline.black.hover.background" },
        { slot: "surface.dark.outline.black.hover.border", token: "component.iconButton.color.dark.outline.black.hover.border" },
        { slot: "surface.dark.outline.black.hover.foreground", token: "component.iconButton.color.dark.outline.black.hover.foreground" },
        { slot: "surface.dark.subtle.primary.rest.background", token: "component.iconButton.color.dark.subtle.primary.rest.background" },
        { slot: "surface.dark.subtle.primary.rest.foreground", token: "component.iconButton.color.dark.subtle.primary.rest.foreground" },
        { slot: "surface.dark.subtle.primary.hover.background", token: "component.iconButton.color.dark.subtle.primary.hover.background" },
        { slot: "surface.dark.subtle.primary.hover.foreground", token: "component.iconButton.color.dark.subtle.primary.hover.foreground" },
        { slot: "surface.dark.subtle.black.rest.background", token: "component.iconButton.color.dark.subtle.black.rest.background" },
        { slot: "surface.dark.subtle.black.rest.foreground", token: "component.iconButton.color.dark.subtle.black.rest.foreground" },
        { slot: "surface.dark.subtle.black.hover.background", token: "component.iconButton.color.dark.subtle.black.hover.background" },
        { slot: "surface.dark.subtle.black.hover.foreground", token: "component.iconButton.color.dark.subtle.black.hover.foreground" },
        { slot: "surface.dark.ghost.primary.rest.background", token: "component.iconButton.color.dark.ghost.primary.rest.background" },
        { slot: "surface.dark.ghost.primary.rest.foreground", token: "component.iconButton.color.dark.ghost.primary.rest.foreground" },
        { slot: "surface.dark.ghost.primary.hover.background", token: "component.iconButton.color.dark.ghost.primary.hover.background" },
        { slot: "surface.dark.ghost.primary.hover.foreground", token: "component.iconButton.color.dark.ghost.primary.hover.foreground" },
        { slot: "surface.dark.ghost.black.rest.background", token: "component.iconButton.color.dark.ghost.black.rest.background" },
        { slot: "surface.dark.ghost.black.rest.foreground", token: "component.iconButton.color.dark.ghost.black.rest.foreground" },
        { slot: "surface.dark.ghost.black.hover.background", token: "component.iconButton.color.dark.ghost.black.hover.background" },
        { slot: "surface.dark.ghost.black.hover.foreground", token: "component.iconButton.color.dark.ghost.black.hover.foreground" },
        { slot: "surface.dark.transparent.rest.background", token: "component.iconButton.color.dark.transparent.rest.background" },
        { slot: "surface.dark.transparent.rest.foreground", token: "component.iconButton.color.dark.transparent.rest.foreground" },
        { slot: "surface.dark.transparent.hover.background", token: "component.iconButton.color.dark.transparent.hover.background" },
        { slot: "surface.dark.transparent.hover.foreground", token: "component.iconButton.color.dark.transparent.hover.foreground" },
        { slot: "surface.dark.disabled.background", token: "component.iconButton.color.dark.disabled.background" },
        { slot: "surface.dark.disabled.border", token: "component.iconButton.color.dark.disabled.border" },
        { slot: "surface.dark.disabled.foreground", token: "component.iconButton.color.dark.disabled.foreground" }
      ],
      themeScopes: ["cars24", "teambhp", "carinfo", "vehicleinfo"]
    },
    {
      canonicalId: "component.accordion",
      canonicalName: "Accordion",
      layer: "component",
      status: "approved",
      platform: "shared",
      figmaComponentName: "Accordion",
      description:
        "Expandable content container that reveals or hides related information within the same layout.",
      webExport: "@geist/web/canonical/accordion",
      nativeExport: "@geist/native/canonical/accordion",
      variants: [
        { name: "size", values: ["sm", "lg"] },
        { name: "selectionMode", values: ["single", "multiple"] }
      ],
      states: ["default", "hover", "focus", "active", "disabled", "expanded", "collapsed"],
      tokenBindings: [
        { slot: "container.background.rest", token: "var(--cars24-semantic-bg-primary)" },
        { slot: "container.background.hover", token: "var(--cars24-semantic-bg-primary-hover)" },
        { slot: "container.border", token: "var(--cars24-semantic-border-primary)" },
        { slot: "container.focusRing", token: "color.border.focus" },
        { slot: "radius.container.sm", token: "radius.md" },
        { slot: "radius.container.lg", token: "radius.lg" },
        { slot: "spacing.padding", token: "var(--cars24-misc-gap-16)" },
        { slot: "spacing.headerGap", token: "var(--cars24-misc-gap-12)" },
        { slot: "spacing.sectionGap", token: "var(--cars24-misc-gap-8)" },
        { slot: "spacing.contentGap", token: "var(--cars24-misc-gap-6)" },
        { slot: "spacing.titleGap", token: "var(--cars24-misc-gap-2)" },
        { slot: "icon.size.sm", token: "var(--cars24-misc-size-18)" },
        { slot: "icon.size.lg", token: "var(--cars24-misc-size-20)" },
        { slot: "icon.color.primary", token: "var(--cars24-semantic-icon-primary)" },
        { slot: "icon.color.secondary", token: "var(--cars24-semantic-icon-secondary)" },
        { slot: "content.title.color", token: "var(--cars24-semantic-text-primary)" },
        { slot: "content.supporting.color", token: "var(--cars24-semantic-text-secondary)" },
        { slot: "content.body.color", token: "var(--cars24-semantic-text-secondary)" },
        { slot: "typography.title.fontFamily", token: "var(--cars24-theme-font-family-primary)" },
        { slot: "typography.title.fontWeight", token: "var(--cars24-theme-font-weight-semibold)" },
        { slot: "typography.title.sm", token: "utility/label-2/semibold" },
        { slot: "typography.title.lg", token: "utility/label-1/semibold" },
        { slot: "typography.supporting.fontFamily", token: "var(--cars24-theme-font-family-primary)" },
        { slot: "typography.supporting.fontWeight", token: "var(--cars24-theme-font-weight-regular)" },
        { slot: "typography.supporting.fontSize", token: "var(--cars24-typography-size-utility-label-2)" },
        { slot: "typography.supporting.lineHeight", token: "var(--cars24-typography-line-height-utility-label-2)" },
        { slot: "typography.body", token: "paragraph/body-2" }
      ],
      themeScopes: ["cars24", "teambhp", "carinfo", "vehicleinfo"]
    },
    {
      canonicalId: "component.badge",
      canonicalName: "Badge",
      layer: "component",
      status: "approved",
      platform: "shared",
      figmaComponentName: "Badge",
      description: "Compact indicator used to show count, status, or a short state attached to another element.",
      webExport: "@geist/web/canonical/badge",
      nativeExport: "@geist/native/canonical/badge",
      variants: [
        { name: "size", values: ["Extra Small", "Small", "Medium"] },
        {
          name: "type",
          values: ["Drive pink", "Error", "Feature", "Information", "Neutral", "Sky surge", "Success", "Warning"]
        },
        { name: "priority", values: ["High", "Medium", "Low"] },
        { name: "pillShape", values: ["No", "Yes"] }
      ],
      states: ["default", "hover", "focus", "active", "disabled"],
      tokenBindings: [
        { slot: "spacing.gap.xs", token: "var(--cars24-misc-gap-2)" },
        { slot: "spacing.gap.sm", token: "var(--cars24-misc-gap-2)" },
        { slot: "spacing.gap.md", token: "var(--cars24-misc-gap-4)" },
        { slot: "spacing.padding.xs.inline", token: "var(--cars24-misc-gap-4)" },
        { slot: "spacing.padding.xs.inlinePill", token: "var(--cars24-misc-gap-6)" },
        { slot: "spacing.padding.xs.block", token: "var(--cars24-misc-gap-4)" },
        { slot: "spacing.padding.sm.inline", token: "var(--cars24-misc-gap-4)" },
        { slot: "spacing.padding.sm.inlinePill", token: "var(--cars24-misc-gap-8)" },
        { slot: "spacing.padding.sm.block", token: "var(--cars24-misc-gap-4)" },
        { slot: "spacing.padding.md.inline", token: "var(--cars24-misc-gap-8)" },
        { slot: "spacing.padding.md.inlinePill", token: "var(--cars24-misc-gap-10)" },
        { slot: "spacing.padding.md.block", token: "var(--cars24-misc-gap-8)" },
        { slot: "icon.size.xs", token: "var(--cars24-misc-size-12)" },
        { slot: "icon.size.sm", token: "var(--cars24-misc-size-14)" },
        { slot: "icon.size.md", token: "var(--cars24-misc-size-18)" },
        { slot: "radius.square.xs", token: "var(--cars24-theme-radius-alt-xs)" },
        { slot: "radius.square.sm", token: "var(--cars24-theme-radius-alt-sm)" },
        { slot: "radius.square.md", token: "var(--cars24-theme-radius-alt-md)" },
        { slot: "radius.pill", token: "var(--cars24-theme-radius-full)" },
        { slot: "typography.xs", token: "utility/label-4/medium" },
        { slot: "typography.sm", token: "utility/label-3/medium" },
        { slot: "typography.md", token: "utility/label-1/medium" },
        { slot: "color.drivePink.high.background", token: "var(--cars24-primitive-drive-pink-600)" },
        { slot: "color.drivePink.high.text", token: "var(--cars24-semantic-text-primary-inverse)" },
        { slot: "color.drivePink.medium.background", token: "var(--cars24-primitive-drive-pink-50)" },
        { slot: "color.drivePink.medium.text", token: "var(--cars24-primitive-drive-pink-600)" },
        { slot: "color.drivePink.medium.border", token: "var(--cars24-primitive-drive-pink-600)" },
        { slot: "color.drivePink.low.background", token: "var(--cars24-primitive-drive-pink-50)" },
        { slot: "color.drivePink.low.text", token: "var(--cars24-primitive-drive-pink-600)" },
        { slot: "color.error.high.background", token: "var(--cars24-semantic-bg-danger-base)" },
        { slot: "color.error.high.text", token: "var(--cars24-semantic-text-primary-inverse)" },
        { slot: "color.error.medium.background", token: "var(--cars24-semantic-bg-danger-subtler)" },
        { slot: "color.error.medium.text", token: "var(--cars24-semantic-text-danger-base)" },
        { slot: "color.error.medium.border", token: "var(--cars24-semantic-border-danger-base)" },
        { slot: "color.error.low.background", token: "var(--cars24-semantic-bg-danger-subtler)" },
        { slot: "color.error.low.text", token: "var(--cars24-semantic-text-danger-base)" },
        { slot: "color.feature.high.background", token: "var(--cars24-primitive-pop-purple-500)" },
        { slot: "color.feature.high.text", token: "var(--cars24-semantic-text-primary-inverse)" },
        { slot: "color.feature.medium.background", token: "var(--cars24-primitive-pop-purple-50)" },
        { slot: "color.feature.medium.text", token: "var(--cars24-primitive-pop-purple-500)" },
        { slot: "color.feature.medium.border", token: "var(--cars24-primitive-pop-purple-500)" },
        { slot: "color.feature.low.background", token: "var(--cars24-primitive-pop-purple-50)" },
        { slot: "color.feature.low.text", token: "var(--cars24-primitive-pop-purple-500)" },
        { slot: "color.information.high.background", token: "var(--cars24-semantic-bg-info-base)" },
        { slot: "color.information.high.text", token: "var(--cars24-semantic-text-primary-inverse)" },
        { slot: "color.information.medium.background", token: "var(--cars24-semantic-bg-info-subtler)" },
        { slot: "color.information.medium.text", token: "var(--cars24-semantic-text-info-base)" },
        { slot: "color.information.medium.border", token: "var(--cars24-semantic-bg-info-base)" },
        { slot: "color.information.low.background", token: "var(--cars24-semantic-bg-info-subtler)" },
        { slot: "color.information.low.text", token: "var(--cars24-semantic-text-info-base)" },
        { slot: "color.neutral.high.background", token: "var(--cars24-semantic-bg-primary-inverse)" },
        { slot: "color.neutral.high.text", token: "var(--cars24-semantic-text-primary-inverse)" },
        { slot: "color.neutral.medium.background", token: "var(--cars24-semantic-bg-secondary)" },
        { slot: "color.neutral.medium.text", token: "var(--cars24-semantic-text-secondary)" },
        { slot: "color.neutral.medium.border", token: "var(--cars24-semantic-border-tertiary)" },
        { slot: "color.neutral.low.background", token: "var(--cars24-semantic-bg-tertiary)" },
        { slot: "color.neutral.low.text", token: "var(--cars24-semantic-text-secondary)" },
        { slot: "color.skySurge.high.background", token: "var(--cars24-primitive-sky-surge-700)" },
        { slot: "color.skySurge.high.text", token: "var(--cars24-semantic-text-primary-inverse)" },
        { slot: "color.skySurge.medium.background", token: "var(--cars24-primitive-sky-surge-50)" },
        { slot: "color.skySurge.medium.text", token: "var(--cars24-primitive-sky-surge-700)" },
        { slot: "color.skySurge.medium.border", token: "var(--cars24-primitive-sky-surge-700)" },
        { slot: "color.skySurge.low.background", token: "var(--cars24-primitive-sky-surge-100)" },
        { slot: "color.skySurge.low.text", token: "var(--cars24-primitive-sky-surge-700)" },
        { slot: "color.success.high.background", token: "var(--cars24-semantic-bg-success-base)" },
        { slot: "color.success.high.text", token: "var(--cars24-semantic-text-primary-inverse)" },
        { slot: "color.success.medium.background", token: "var(--cars24-semantic-bg-success-subtler)" },
        { slot: "color.success.medium.text", token: "var(--cars24-semantic-text-success-base)" },
        { slot: "color.success.medium.border", token: "var(--cars24-semantic-border-success-base)" },
        { slot: "color.success.low.background", token: "var(--cars24-semantic-bg-success-subtle)" },
        { slot: "color.success.low.text", token: "var(--cars24-semantic-text-success-base)" },
        { slot: "color.warning.high.background", token: "var(--cars24-semantic-bg-warning-base)" },
        { slot: "color.warning.high.text", token: "var(--cars24-semantic-text-primary-inverse)" },
        { slot: "color.warning.medium.background", token: "var(--cars24-semantic-bg-warning-subtler)" },
        { slot: "color.warning.medium.text", token: "var(--cars24-semantic-text-warning-base)" },
        { slot: "color.warning.medium.border", token: "var(--cars24-semantic-border-warning-base)" },
        { slot: "color.warning.low.background", token: "var(--cars24-semantic-bg-warning-subtle)" },
        { slot: "color.warning.low.text", token: "var(--cars24-semantic-text-warning-base)" }
      ],
      themeScopes: ["cars24", "teambhp", "carinfo", "vehicleinfo"]
    },
    {
      canonicalId: "component.banner",
      canonicalName: "Banner",
      layer: "component",
      status: "approved",
      platform: "shared",
      figmaComponentName: "Banner",
      description: "Inline notification surface for status messaging with optional icon and action.",
      webExport: "@geist/web/canonical/banner",
      nativeExport: "@geist/native/canonical/banner",
      variants: [
        { name: "theme", values: ["Light", "Dark"] },
        { name: "state", values: ["Warning", "Success", "Error", "Info", "Brand"] },
        { name: "heading", values: ["true", "false"] },
        { name: "icon", values: ["true", "false"] },
        { name: "action", values: ["true", "false"] },
        { name: "actionType", values: ["Text button", "Icon button"] },
        { name: "title", values: ["New Message Alert"] },
        { name: "description", values: ["New message received!"] }
      ],
      states: ["default"],
      tokenBindings: [
        { slot: "container.width", token: "328px" },
        { slot: "container.radius", token: "var(--cars24-theme-radius-alt-lg)" },
        { slot: "container.shadow", token: "drop-shadow/xl" },
        { slot: "container.gap", token: "var(--cars24-misc-gap-none)" },
        { slot: "container.focusRing", token: "color.border.focus" },
        { slot: "content.gap", token: "var(--cars24-misc-gap-8)" },
        { slot: "content.paddingInline", token: "var(--cars24-misc-gap-12)" },
        { slot: "content.paddingBlock", token: "var(--cars24-misc-gap-16)" },
        { slot: "content.title", token: "utility/label-1/medium" },
        { slot: "content.description.sm", token: "paragraph/body-3" },
        { slot: "content.description.md", token: "paragraph/body-2" },
        { slot: "icon.leading.size", token: "var(--cars24-misc-size-20)" },
        { slot: "icon.action.size", token: "var(--cars24-misc-size-24)" },
        { slot: "action.text.radius", token: "var(--cars24-theme-radius-full)" },
        { slot: "action.text.paddingInline", token: "var(--cars24-misc-gap-12)" },
        { slot: "action.text.paddingBlock", token: "var(--cars24-misc-gap-6)" },
        { slot: "action.text.typography", token: "utility/label-3/medium" },
        { slot: "action.focusRing", token: "color.border.focus" },
        { slot: "tone.light.warning.background", token: "var(--cars24-semantic-bg-warning-subtler)" },
        { slot: "tone.light.warning.border", token: "var(--cars24-semantic-border-warning-subtle)" },
        { slot: "tone.light.warning.icon", token: "var(--cars24-semantic-icon-warning-base)" },
        { slot: "tone.light.warning.title", token: "var(--cars24-semantic-text-primary)" },
        { slot: "tone.light.warning.description", token: "var(--cars24-semantic-text-secondary)" },
        { slot: "tone.light.success.background", token: "var(--cars24-semantic-bg-success-subtler)" },
        { slot: "tone.light.success.border", token: "var(--cars24-semantic-border-success-subtle)" },
        { slot: "tone.light.success.icon", token: "var(--cars24-semantic-icon-success-base)" },
        { slot: "tone.light.success.title", token: "var(--cars24-semantic-text-primary)" },
        { slot: "tone.light.success.description", token: "var(--cars24-semantic-text-secondary)" },
        { slot: "tone.light.error.background", token: "var(--cars24-semantic-bg-danger-subtler)" },
        { slot: "tone.light.error.border", token: "var(--cars24-semantic-border-danger-subtle)" },
        { slot: "tone.light.error.icon", token: "var(--cars24-semantic-icon-danger-base)" },
        { slot: "tone.light.error.title", token: "var(--cars24-semantic-text-primary)" },
        { slot: "tone.light.error.description", token: "var(--cars24-semantic-text-secondary)" },
        { slot: "tone.light.info.background", token: "var(--cars24-semantic-bg-info-subtler)" },
        { slot: "tone.light.info.border", token: "var(--cars24-semantic-border-info-subtle)" },
        { slot: "tone.light.info.icon", token: "var(--cars24-semantic-icon-info-base)" },
        { slot: "tone.light.info.title", token: "var(--cars24-semantic-text-primary)" },
        { slot: "tone.light.info.description", token: "var(--cars24-semantic-text-secondary)" },
        { slot: "tone.light.brand.background", token: "var(--cars24-semantic-bg-brand-subtler)" },
        { slot: "tone.light.brand.border", token: "var(--cars24-semantic-border-brand-subtle)" },
        { slot: "tone.light.brand.icon", token: "var(--cars24-semantic-icon-brand-base)" },
        { slot: "tone.light.brand.title", token: "var(--cars24-semantic-text-primary)" },
        { slot: "tone.light.brand.description", token: "var(--cars24-semantic-text-secondary)" },
        { slot: "tone.dark.warning.background", token: "var(--cars24-semantic-bg-warning-base)" },
        { slot: "tone.dark.warning.border", token: "transparent" },
        { slot: "tone.dark.warning.icon", token: "var(--cars24-semantic-icon-primary-inverse)" },
        { slot: "tone.dark.warning.title", token: "var(--cars24-semantic-text-primary-inverse)" },
        { slot: "tone.dark.warning.description", token: "var(--cars24-semantic-text-primary-inverse)" },
        { slot: "tone.dark.success.background", token: "var(--cars24-semantic-bg-success-base)" },
        { slot: "tone.dark.success.border", token: "transparent" },
        { slot: "tone.dark.success.icon", token: "var(--cars24-semantic-icon-primary-inverse)" },
        { slot: "tone.dark.success.title", token: "var(--cars24-semantic-text-primary-inverse)" },
        { slot: "tone.dark.success.description", token: "var(--cars24-semantic-text-primary-inverse)" },
        { slot: "tone.dark.error.background", token: "var(--cars24-semantic-bg-danger-base)" },
        { slot: "tone.dark.error.border", token: "transparent" },
        { slot: "tone.dark.error.icon", token: "var(--cars24-semantic-icon-primary-inverse)" },
        { slot: "tone.dark.error.title", token: "var(--cars24-semantic-text-primary-inverse)" },
        { slot: "tone.dark.error.description", token: "var(--cars24-semantic-text-primary-inverse)" },
        { slot: "tone.dark.info.background", token: "var(--cars24-semantic-bg-info-base)" },
        { slot: "tone.dark.info.border", token: "transparent" },
        { slot: "tone.dark.info.icon", token: "var(--cars24-semantic-icon-primary-inverse)" },
        { slot: "tone.dark.info.title", token: "var(--cars24-semantic-text-primary-inverse)" },
        { slot: "tone.dark.info.description", token: "var(--cars24-semantic-text-primary-inverse)" },
        { slot: "tone.dark.brand.background", token: "var(--cars24-semantic-bg-brand-base)" },
        { slot: "tone.dark.brand.border", token: "transparent" },
        { slot: "tone.dark.brand.icon", token: "var(--cars24-semantic-icon-primary-inverse)" },
        { slot: "tone.dark.brand.title", token: "var(--cars24-semantic-text-primary-inverse)" },
        { slot: "tone.dark.brand.description", token: "var(--cars24-semantic-text-primary-inverse)" },
        { slot: "action.light.background", token: "var(--cars24-semantic-bg-primary-inverse)" },
        { slot: "action.light.text", token: "var(--cars24-semantic-text-primary-inverse)" },
        { slot: "action.light.icon", token: "var(--cars24-semantic-icon-secondary)" },
        { slot: "action.dark.background", token: "var(--cars24-semantic-bg-primary)" },
        { slot: "action.dark.text", token: "var(--cars24-semantic-text-primary)" },
        { slot: "action.dark.icon", token: "var(--cars24-semantic-icon-primary-inverse)" },
        { slot: "action.light.warning.background", token: "var(--cars24-semantic-bg-primary-inverse)" },
        { slot: "action.light.warning.text", token: "var(--cars24-semantic-text-primary-inverse)" },
        { slot: "action.light.warning.icon", token: "var(--cars24-semantic-icon-secondary)" },
        { slot: "action.light.success.background", token: "var(--cars24-semantic-bg-primary-inverse)" },
        { slot: "action.light.success.text", token: "var(--cars24-semantic-text-primary-inverse)" },
        { slot: "action.light.success.icon", token: "var(--cars24-semantic-icon-secondary)" },
        { slot: "action.light.error.background", token: "var(--cars24-semantic-bg-primary-inverse)" },
        { slot: "action.light.error.text", token: "var(--cars24-semantic-text-primary-inverse)" },
        { slot: "action.light.error.icon", token: "var(--cars24-semantic-icon-secondary)" },
        { slot: "action.light.info.background", token: "var(--cars24-semantic-bg-primary-inverse)" },
        { slot: "action.light.info.text", token: "var(--cars24-semantic-text-primary-inverse)" },
        { slot: "action.light.info.icon", token: "var(--cars24-semantic-icon-secondary)" },
        { slot: "action.light.brand.background", token: "var(--cars24-semantic-bg-primary-inverse)" },
        { slot: "action.light.brand.text", token: "var(--cars24-semantic-text-primary-inverse)" },
        { slot: "action.light.brand.icon", token: "var(--cars24-semantic-icon-secondary)" },
        { slot: "action.dark.warning.background", token: "var(--cars24-semantic-bg-primary)" },
        { slot: "action.dark.warning.text", token: "var(--cars24-semantic-text-primary)" },
        { slot: "action.dark.warning.icon", token: "var(--cars24-semantic-icon-primary-inverse)" },
        { slot: "action.dark.success.background", token: "var(--cars24-semantic-bg-primary)" },
        { slot: "action.dark.success.text", token: "var(--cars24-semantic-text-primary)" },
        { slot: "action.dark.success.icon", token: "var(--cars24-semantic-icon-primary-inverse)" },
        { slot: "action.dark.error.background", token: "var(--cars24-semantic-bg-primary)" },
        { slot: "action.dark.error.text", token: "var(--cars24-semantic-text-primary)" },
        { slot: "action.dark.error.icon", token: "var(--cars24-semantic-icon-primary-inverse)" },
        { slot: "action.dark.info.background", token: "var(--cars24-semantic-bg-primary)" },
        { slot: "action.dark.info.text", token: "var(--cars24-semantic-text-primary)" },
        { slot: "action.dark.info.icon", token: "var(--cars24-semantic-icon-primary-inverse)" },
        { slot: "action.dark.brand.background", token: "var(--cars24-semantic-bg-primary)" },
        { slot: "action.dark.brand.text", token: "var(--cars24-semantic-text-primary)" },
        { slot: "action.dark.brand.icon", token: "var(--cars24-semantic-icon-primary-inverse)" }
      ],
      themeScopes: ["cars24", "teambhp", "carinfo", "vehicleinfo"]
    },
    {
      canonicalId: "component.sectionHeader",
      canonicalName: "Section Header",
      layer: "component",
      status: "approved",
      platform: "shared",
      figmaComponentName: "Section Text Header",
      description: "Section heading block with optional second title line, supporting description, tag, and trailing action.",
      webExport: "@geist/web/canonical/section-header",
      nativeExport: "@geist/native/canonical/section-header",
      variants: [
        { name: "inverse", values: ["false", "true"] },
        { name: "showTag", values: ["false", "true"] },
        { name: "showAction", values: ["false", "true"] },
        { name: "showDescription", values: ["false", "true"] },
        { name: "showSubtitle", values: ["false", "true"] },
        { name: "titleIcon", values: ["false", "true"] },
        { name: "subtitleIcon", values: ["false", "true"] }
      ],
      states: ["default"],
      tokenBindings: [
        { slot: "container.width", token: "component.sectionHeader.size.width" },
        { slot: "container.gap", token: "component.sectionHeader.size.gap" },
        { slot: "container.paddingBottom", token: "component.sectionHeader.size.paddingBottom" },
        { slot: "layout.variant", token: "component.sectionHeader.layout.variant" },
        { slot: "layout.rowGap", token: "component.sectionHeader.size.rowGap" },
        { slot: "layout.contentGap", token: "component.sectionHeader.size.contentGap" },
        { slot: "layout.titleRowGap", token: "component.sectionHeader.size.titleRowGap" },
        { slot: "layout.titleStackGap", token: "component.sectionHeader.size.titleStackGap" },
        { slot: "layout.actionGap", token: "component.sectionHeader.size.actionGap" },
        { slot: "layout.actionStackGap", token: "component.sectionHeader.size.actionStackGap" },
        { slot: "icon.size", token: "component.sectionHeader.size.iconSize" },
        { slot: "divider.gap", token: "component.sectionHeader.size.dividerGap" },
        { slot: "divider.thickness", token: "component.sectionHeader.size.dividerThickness" },
        { slot: "typography.title.fontFamily", token: "typography.fontFamily.sans" },
        { slot: "typography.title.fontWeight", token: "typography.fontWeight.semibold" },
        { slot: "typography.title.fontSize", token: "component.sectionHeader.typography.title.fontSize" },
        { slot: "typography.title.lineHeight", token: "component.sectionHeader.typography.title.lineHeight" },
        { slot: "typography.title.letterSpacing", token: "component.sectionHeader.typography.title.letterSpacing" },
        { slot: "typography.description.fontFamily", token: "typography.fontFamily.sans" },
        { slot: "typography.description.fontWeight", token: "typography.fontWeight.regular" },
        { slot: "typography.description.fontSize", token: "component.sectionHeader.typography.description.fontSize" },
        { slot: "typography.description.lineHeight", token: "component.sectionHeader.typography.description.lineHeight" },
        { slot: "typography.description.letterSpacing", token: "component.sectionHeader.typography.description.letterSpacing" },
        { slot: "tag.height", token: "component.sectionHeader.size.tagHeight" },
        { slot: "tag.paddingInline", token: "component.sectionHeader.size.tagPaddingInline" },
        { slot: "tag.paddingBlock", token: "component.sectionHeader.size.tagPaddingBlock" },
        { slot: "tag.radius", token: "radius.pill" },
        { slot: "tag.typography.fontFamily", token: "typography.fontFamily.sans" },
        { slot: "tag.typography.fontWeight", token: "typography.fontWeight.medium" },
        { slot: "tag.typography.fontSize", token: "component.sectionHeader.typography.tag.fontSize" },
        { slot: "tag.typography.lineHeight", token: "component.sectionHeader.typography.tag.lineHeight" },
        { slot: "tag.typography.letterSpacing", token: "component.sectionHeader.typography.tag.letterSpacing" },
        { slot: "action.height", token: "component.linkButton.size.sm.height" },
        { slot: "action.typography.fontSize", token: "component.linkButton.typography.sm.fontSize" },
        { slot: "action.typography.lineHeight", token: "component.linkButton.typography.sm.lineHeight" },
        { slot: "action.typography.letterSpacing", token: "component.linkButton.typography.sm.letterSpacing" },
        { slot: "action.foreground.light", token: "component.linkButton.color.light.brand.rest" },
        { slot: "action.foreground.dark", token: "component.linkButton.color.dark.brand.rest" },
        { slot: "color.light.title", token: "component.sectionHeader.color.light.title" },
        { slot: "color.light.description", token: "component.sectionHeader.color.light.description" },
        { slot: "color.light.divider", token: "component.sectionHeader.color.light.divider" },
        { slot: "color.light.dividerOpaque", token: "component.sectionHeader.color.light.dividerOpaque" },
        { slot: "color.light.dividerTransparent", token: "component.sectionHeader.color.light.dividerTransparent" },
        { slot: "color.dark.title", token: "component.sectionHeader.color.dark.title" },
        { slot: "color.dark.description", token: "component.sectionHeader.color.dark.description" },
        { slot: "color.dark.divider", token: "component.sectionHeader.color.dark.divider" },
        { slot: "color.dark.dividerOpaque", token: "component.sectionHeader.color.dark.dividerOpaque" },
        { slot: "color.dark.dividerTransparent", token: "component.sectionHeader.color.dark.dividerTransparent" },
        { slot: "color.tag.background", token: "component.sectionHeader.color.tag.background" },
        { slot: "color.tag.foreground", token: "component.sectionHeader.color.tag.foreground" }
      ],
      themeScopes: ["cars24", "teambhp", "carinfo", "vehicleinfo"]
    },
    {
      canonicalId: "component.divider",
      canonicalName: "Divider",
      layer: "component",
      status: "approved",
      platform: "shared",
      figmaComponentName: "divider",
      description: "Visual separator with optional token-driven label content and left, center, or right alignment.",
      webExport: "@geist/web/canonical/divider",
      nativeExport: "@geist/native/canonical/divider",
      variants: [
        { name: "labelPosition", values: ["None", "Center", "Left", "Right"] },
        { name: "thickness", values: ["Regular", "Thin"] },
        { name: "lineStyle", values: ["Plain", "Dash"] },
        { name: "showContent", values: ["false", "true"] }
      ],
      states: ["default"],
      tokenBindings: [
        { slot: "container.width", token: "component.divider.size.width" },
        { slot: "line.shortSegmentLength", token: "component.divider.size.shortSegmentLength" },
        { slot: "line.thickness.regular", token: "component.divider.size.thickness.regular" },
        { slot: "line.thickness.thin", token: "component.divider.size.thickness.thin" },
        { slot: "content.gap", token: "component.divider.size.contentGap" },
        { slot: "content.paddingInline", token: "component.divider.size.contentPaddingInline" },
        { slot: "content.paddingBlock", token: "component.divider.size.contentPaddingBlock" },
        { slot: "content.radius.regular", token: "component.divider.size.contentRadius.regular" },
        { slot: "content.radius.thin", token: "component.divider.size.contentRadius.thin" },
        { slot: "icon.size", token: "component.divider.size.iconSize" },
        { slot: "typography.label.fontFamily", token: "typography.fontFamily.sans" },
        { slot: "typography.label.fontWeight", token: "typography.fontWeight.regular" },
        { slot: "typography.label.fontSize", token: "component.divider.typography.label.fontSize" },
        { slot: "typography.label.lineHeight", token: "component.divider.typography.label.lineHeight" },
        { slot: "typography.label.letterSpacing", token: "component.divider.typography.label.letterSpacing" },
        { slot: "color.line", token: "component.divider.color.line" },
        { slot: "color.content", token: "component.divider.color.content" }
      ],
      themeScopes: ["cars24", "teambhp", "carinfo", "vehicleinfo"]
    }
  ],
  widgets: [
    {
      canonicalId: "widget.auth-card",
      canonicalName: "Auth Card",
      layer: "widget",
      status: "approved",
      platform: "shared",
      description: "Composable authentication surface built from approved components.",
      composition: ["component.button"],
      allowedChildren: ["component.button"]
    }
  ],
  pages: [
    {
      canonicalId: "page.sign-in",
      canonicalName: "Sign In",
      layer: "page",
      status: "approved",
      platform: "shared",
      description: "Login page assembled only from approved widgets and components.",
      composition: ["widget.auth-card"]
    }
  ],
  flows: [
    {
      canonicalId: "flow.authentication",
      canonicalName: "Authentication Flow",
      layer: "flow",
      status: "approved",
      platform: "shared",
      description: "A governed sequence of pages for signing in and recovery.",
      pages: ["page.sign-in"]
    }
  ]
};
